import { ProviderConfig, LanguageOption, VoiceOption, ModelOption } from './ProviderConfig';

export class GeminiProviderConfig {
  private static readonly LANGUAGES: LanguageOption[] = [
    { name: 'Аԥсуа', value: 'ab', englishName: 'Abkhaz' },
    { name: 'Bahsa Acèh', value: 'ace', englishName: 'Acehnese' },
    { name: 'Lwo', value: 'ach', englishName: 'Acholi' },
    { name: 'Qafar af', value: 'aa', englishName: 'Afar' },
    { name: 'Afrikaans', value: 'af', englishName: 'Afrikaans' },
    { name: 'Aklanon', value: 'akl', englishName: 'Aklanon' },
    { name: 'Shqip', value: 'sq', englishName: 'Albanian' },
    { name: 'Dho Alur', value: 'alz', englishName: 'Alur' },
    { name: 'አማርኛ', value: 'am', englishName: 'Amharic' },
    { name: 'العربية', value: 'ar', englishName: 'Arabic' },
    { name: 'Հայերեն', value: 'hy', englishName: 'Armenian' },
    { name: 'অসমীয়া', value: 'as', englishName: 'Assamese' },
    { name: 'Авар мацӏ', value: 'av', englishName: 'Avar' },
    { name: 'अवधी', value: 'awa', englishName: 'Awadhi' },
    { name: 'Aymar aru', value: 'ay', englishName: 'Aymara' },
    { name: 'Azərbaycan', value: 'az', englishName: 'Azerbaijani' },
    { name: 'Basa Bali', value: 'ban', englishName: 'Balinese' },
    { name: 'بلوچی', value: 'bal', englishName: 'Baluchi' },
    { name: 'Bamanankan', value: 'bm', englishName: 'Bambara' },
    { name: 'Baoulé', value: 'bci', englishName: 'Baoulé' },
    { name: 'Башҡорт', value: 'ba', englishName: 'Bashkir' },
    { name: 'Euskara', value: 'eu', englishName: 'Basque' },
    { name: 'Batak Karo', value: 'btx', englishName: 'Batak Karo' },
    { name: 'Batak Simalungun', value: 'bts', englishName: 'Batak Simalungun' },
    { name: 'Batak Toba', value: 'bbc', englishName: 'Batak Toba' },
    { name: 'Беларуская', value: 'be', englishName: 'Belarusian' },
    { name: 'Ichibemba', value: 'bem', englishName: 'Bemba' },
    { name: 'বাংলা', value: 'bn', englishName: 'Bengali' },
    { name: 'Betawi', value: 'bew', englishName: 'Betawi' },
    { name: 'भोजपुरी', value: 'bho', englishName: 'Bhojpuri' },
    { name: 'Bikol', value: 'bik', englishName: 'Bikol' },
    { name: 'Bosanski', value: 'bs', englishName: 'Bosnian' },
    { name: 'Brezhoneg', value: 'br', englishName: 'Breton' },
    { name: 'Български', value: 'bg', englishName: 'Bulgarian' },
    { name: 'Буряад', value: 'bua', englishName: 'Buryat' },
    { name: '廣東話', value: 'yue', englishName: 'Cantonese' },
    { name: 'Català', value: 'ca', englishName: 'Catalan' },
    { name: 'Cebuano', value: 'ceb', englishName: 'Cebuano' },
    { name: 'Chamoru', value: 'ch', englishName: 'Chamorro' },
    { name: 'Chavacano', value: 'cbk', englishName: 'Chavacano' },
    { name: 'Нохчийн', value: 'ce', englishName: 'Chechen' },
    { name: 'Chichewa', value: 'ny', englishName: 'Chichewa' },
    { name: '中文（简体）', value: 'zh-CN', englishName: 'Chinese (Simplified)' },
    { name: '中文（繁體）', value: 'zh-TW', englishName: 'Chinese (Traditional)' },
    { name: 'Chuukese', value: 'chk', englishName: 'Chuukese' },
    { name: 'Чӑвашла', value: 'cv', englishName: 'Chuvash' },
    { name: 'Corsu', value: 'co', englishName: 'Corsican' },
    { name: 'Къырымтатар (Кирил)', value: 'crh-Cyrl', englishName: 'Crimean Tatar (Cyrillic)' },
    { name: 'Qırımtatar (Latin)', value: 'crh-Latn', englishName: 'Crimean Tatar (Latin)' },
    { name: 'Hrvatski', value: 'hr', englishName: 'Croatian' },
    { name: 'Čeština', value: 'cs', englishName: 'Czech' },
    { name: 'Dansk', value: 'da', englishName: 'Danish' },
    { name: 'دری', value: 'prs', englishName: 'Dari' },
    { name: 'ދިވެހި', value: 'dv', englishName: 'Dhivehi' },
    { name: 'Thuɔŋjäŋ', value: 'din', englishName: 'Dinka' },
    { name: 'डोगरी', value: 'doi', englishName: 'Dogri' },
    { name: 'Dombe', value: 'dov', englishName: 'Dombe' },
    { name: 'Nederlands', value: 'nl', englishName: 'Dutch' },
    { name: 'Nederlands (België)', value: 'nl-BE', englishName: 'Dutch (Belgium)' },
    { name: 'Nederlands (Nederland)', value: 'nl-NL', englishName: 'Dutch (Netherlands)' },
    { name: 'Nederlands (Suriname)', value: 'nl-SR', englishName: 'Dutch (Suriname)' },
    { name: 'Julakan', value: 'dyu', englishName: 'Dyula' },
    { name: 'རྫོང་ཁ', value: 'dz', englishName: 'Dzongkha' },
    { name: 'English', value: 'en', englishName: 'English' },
    { name: 'English (Australia)', value: 'en-AU', englishName: 'English (Australia)' },
    { name: 'English (India)', value: 'en-IN', englishName: 'English (India)' },
    { name: 'English (United Kingdom)', value: 'en-GB', englishName: 'English (United Kingdom)' },
    { name: 'English (United States)', value: 'en-US', englishName: 'English (United States)' },
    { name: 'Esperanto', value: 'eo', englishName: 'Esperanto' },
    { name: 'Eesti', value: 'et', englishName: 'Estonian' },
    { name: 'Eʋegbe', value: 'ee', englishName: 'Ewe' },
    { name: 'Føroyskt', value: 'fo', englishName: 'Faroese' },
    { name: 'Vosa Vakaviti', value: 'fj', englishName: 'Fijian' },
    { name: 'Filipino', value: 'fil', englishName: 'Filipino' },
    { name: 'Suomi', value: 'fi', englishName: 'Finnish' },
    { name: 'Fɔngbe', value: 'fon', englishName: 'Fon' },
    { name: 'Français', value: 'fr', englishName: 'French' },
    { name: 'Français (Canada)', value: 'fr-CA', englishName: 'French (Canada)' },
    { name: 'Frysk', value: 'fy', englishName: 'Frisian' },
    { name: 'Furlan', value: 'fur', englishName: 'Friulian' },
    { name: 'Fulfulde', value: 'ff', englishName: 'Fulani' },
    { name: 'Gã', value: 'gaa', englishName: 'Ga' },
    { name: 'Galego', value: 'gl', englishName: 'Galician' },
    { name: 'ქართული', value: 'ka', englishName: 'Georgian' },
    { name: 'Deutsch', value: 'de', englishName: 'German' },
    { name: 'Ελληνικά', value: 'el', englishName: 'Greek' },
    { name: 'Guarani', value: 'gn', englishName: 'Guarani' },
    { name: 'ગુજરાતી', value: 'gu', englishName: 'Gujarati' },
    { name: 'Kreyòl Ayisyen', value: 'ht', englishName: 'Haitian Creole' },
    { name: 'Hakha Chin', value: 'cnh', englishName: 'Hakha Chin' },
    { name: 'Hausa', value: 'ha', englishName: 'Hausa' },
    { name: 'ʻŌlelo Hawaiʻi', value: 'haw', englishName: 'Hawaiian' },
    { name: 'עברית', value: 'he', englishName: 'Hebrew' },
    { name: 'Hiligaynon', value: 'hil', englishName: 'Hiligaynon' },
    { name: 'हिन्दी', value: 'hi', englishName: 'Hindi' },
    { name: 'Hmong', value: 'hmn', englishName: 'Hmong' },
    { name: 'Magyar', value: 'hu', englishName: 'Hungarian' },
    { name: 'Hunsrik', value: 'hrx', englishName: 'Hunsrik' },
    { name: 'Iban', value: 'iba', englishName: 'Iban' },
    { name: 'Ibanag', value: 'ibg', englishName: 'Ibanag' },
    { name: 'Íslenska', value: 'is', englishName: 'Icelandic' },
    { name: 'Igbo', value: 'ig', englishName: 'Igbo' },
    { name: 'Ilocano', value: 'ilo', englishName: 'Ilocano' },
    { name: 'Bahasa Indonesia', value: 'id', englishName: 'Indonesian' },
    { name: 'ᐃᓄᒃᑎᑐᑦ (Latin)', value: 'iu-Latn', englishName: 'Inuktut (Latin)' },
    { name: 'ᐃᓄᒃᑎᑐᑦ', value: 'iu', englishName: 'Inuktut (Syllabics)' },
    { name: 'Gaeilge', value: 'ga', englishName: 'Irish' },
    { name: 'Italiano', value: 'it', englishName: 'Italian' },
    { name: 'Ivatan', value: 'ivv', englishName: 'Ivatan' },
    { name: 'Jamaican Patois', value: 'jam', englishName: 'Jamaican Patois' },
    { name: '日本語', value: 'ja', englishName: 'Japanese' },
    { name: 'ꦧꦱꦗꦮ', value: 'jv', englishName: 'Javanese' },
    { name: 'Jingpo', value: 'kac', englishName: 'Jingpo' },
    { name: 'Kalaallisut', value: 'kl', englishName: 'Kalaallisut' },
    { name: 'ಕನ್ನಡ', value: 'kn', englishName: 'Kannada' },
    { name: 'Kanuri', value: 'kr', englishName: 'Kanuri' },
    { name: 'Kapampangan', value: 'pam', englishName: 'Kapampangan' },
    { name: 'Қазақ', value: 'kk', englishName: 'Kazakh' },
    { name: 'Khasi', value: 'kha', englishName: 'Khasi' },
    { name: 'ខ្មែរ', value: 'km', englishName: 'Khmer' },
    { name: 'Kiga', value: 'cgg', englishName: 'Kiga' },
    { name: 'Kikongo', value: 'kg', englishName: 'Kikongo' },
    { name: 'Kinaray-a', value: 'krj', englishName: 'Kinaray-a' },
    { name: 'Kinyarwanda', value: 'rw', englishName: 'Kinyarwanda' },
    { name: 'Kituba', value: 'mkw', englishName: 'Kituba' },
    { name: 'Kokborok', value: 'trp', englishName: 'Kokborok' },
    { name: 'Коми', value: 'kv', englishName: 'Komi' },
    { name: 'कोंकणी', value: 'kok', englishName: 'Konkani' },
    { name: '한국어', value: 'ko', englishName: 'Korean' },
    { name: 'Krio', value: 'kri', englishName: 'Krio' },
    { name: 'Kurdî (Kurmancî)', value: 'ku', englishName: 'Kurdish (Kurmanji)' },
    { name: 'کوردی (سۆرانی)', value: 'ckb', englishName: 'Kurdish (Sorani)' },
    { name: 'Кыргызча', value: 'ky', englishName: 'Kyrgyz' },
    { name: 'ລາວ', value: 'lo', englishName: 'Lao' },
    { name: 'Latgaļu', value: 'ltg', englishName: 'Latgalian' },
    { name: 'Latina', value: 'la', englishName: 'Latin' },
    { name: 'Latviešu', value: 'lv', englishName: 'Latvian' },
    { name: 'Lìgure', value: 'lij', englishName: 'Ligurian' },
    { name: 'Limburgs', value: 'li', englishName: 'Limburgish' },
    { name: 'Lingála', value: 'ln', englishName: 'Lingala' },
    { name: 'Lietuvių', value: 'lt', englishName: 'Lithuanian' },
    { name: 'Lombard', value: 'lmo', englishName: 'Lombard' },
    { name: 'Nedersaksisch', value: 'nds-NL', englishName: 'Low Saxon (Netherlands)' },
    { name: 'Luganda', value: 'lg', englishName: 'Luganda' },
    { name: 'Dholuo', value: 'luo', englishName: 'Luo' },
    { name: 'Lëtzebuergesch', value: 'lb', englishName: 'Luxembourgish' },
    { name: 'Македонски', value: 'mk', englishName: 'Macedonian' },
    { name: 'Madhurâ', value: 'mad', englishName: 'Madurese' },
    { name: 'Maguindanao', value: 'mdh', englishName: 'Maguindanao' },
    { name: 'मैथिली', value: 'mai', englishName: 'Maithili' },
    { name: 'Makassar', value: 'mak', englishName: 'Makassar' },
    { name: 'Malagasy', value: 'mg', englishName: 'Malagasy' },
    { name: 'Bahasa Melayu', value: 'ms', englishName: 'Malay' },
    { name: 'بهاس ملايو (جاوي)', value: 'ms-Arab', englishName: 'Malay (Jawi)' },
    { name: 'മലയാളം', value: 'ml', englishName: 'Malayalam' },
    { name: 'Malti', value: 'mt', englishName: 'Maltese' },
    { name: 'Mam', value: 'mam', englishName: 'Mam' },
    { name: 'Gaelg', value: 'gv', englishName: 'Manx' },
    { name: 'Te Reo Māori', value: 'mi', englishName: 'Maori' },
    { name: 'Maranao', value: 'mrw', englishName: 'Maranao' },
    { name: 'मराठी', value: 'mr', englishName: 'Marathi' },
    { name: 'Kajin Majōl', value: 'mh', englishName: 'Marshallese' },
    { name: 'मारवाड़ी', value: 'mwr', englishName: 'Marwadi' },
    { name: 'Kreol Morisien', value: 'mfe', englishName: 'Mauritian Creole' },
    { name: 'Олык марий', value: 'mhr', englishName: 'Meadow Mari' },
    { name: 'ꯃꯤꯇꯩꯂꯣꯟ', value: 'mni', englishName: 'Meiteilon (Manipuri)' },
    { name: 'Baso Minang', value: 'min', englishName: 'Minang' },
    { name: 'Mizo ṭawng', value: 'lus', englishName: 'Mizo' },
    { name: 'Монгол', value: 'mn', englishName: 'Mongolian' },
    { name: 'မြန်မာ', value: 'my', englishName: 'Myanmar (Burmese)' },
    { name: 'Nahuatl', value: 'nhe', englishName: 'Nahuatl (Eastern Huasteca)' },
    { name: 'Ndau', value: 'ndc', englishName: 'Ndau' },
    { name: 'isiNdebele', value: 'nr', englishName: 'Ndebele (South)' },
    { name: 'नेपालभाषा', value: 'new', englishName: 'Nepalbhasa (Newari)' },
    { name: 'नेपाली', value: 'ne', englishName: 'Nepali' },
    { name: 'ߒߞߏ', value: 'nqo', englishName: 'NKo' },
    { name: 'Norsk', value: 'no', englishName: 'Norwegian' },
    { name: 'Thok Nath', value: 'nus', englishName: 'Nuer' },
    { name: 'Occitan', value: 'oc', englishName: 'Occitan' },
    { name: 'ଓଡ଼ିଆ', value: 'or', englishName: 'Odia (Oriya)' },
    { name: 'Oromoo', value: 'om', englishName: 'Oromo' },
    { name: 'Ирон', value: 'os', englishName: 'Ossetian' },
    { name: 'Pangasinan', value: 'pag', englishName: 'Pangasinan' },
    { name: 'Papiamento', value: 'pap', englishName: 'Papiamento' },
    { name: 'پښتو', value: 'ps', englishName: 'Pashto' },
    { name: 'فارسی', value: 'fa', englishName: 'Persian' },
    { name: 'Polski', value: 'pl', englishName: 'Polish' },
    { name: 'Português (Brasil)', value: 'pt-BR', englishName: 'Portuguese (Brazil)' },
    { name: 'Português (Portugal)', value: 'pt-PT', englishName: 'Portuguese (Portugal)' },
    { name: 'ਪੰਜਾਬੀ (ਗੁਰਮੁਖੀ)', value: 'pa', englishName: 'Punjabi (Gurmukhi)' },
    { name: 'پنجابی (شاہ مکھی)', value: 'pa-Arab', englishName: 'Punjabi (Shahmukhi)' },
    { name: 'Runasimi', value: 'qu', englishName: 'Quechua' },
    { name: 'Qʼeqchiʼ', value: 'kek', englishName: 'Qʼeqchiʼ' },
    { name: 'Romani', value: 'rom', englishName: 'Romani' },
    { name: 'Română', value: 'ro', englishName: 'Romanian' },
    { name: 'Ikirundi', value: 'rn', englishName: 'Rundi' },
    { name: 'Русский', value: 'ru', englishName: 'Russian' },
    { name: 'Davvisámegiella', value: 'se', englishName: 'Sami (North)' },
    { name: 'Gagana Samoa', value: 'sm', englishName: 'Samoan' },
    { name: 'Sängö', value: 'sg', englishName: 'Sango' },
    { name: 'संस्कृतम्', value: 'sa', englishName: 'Sanskrit' },
    { name: 'Santali (Latin)', value: 'sat-Latn', englishName: 'Santali (Latin)' },
    { name: 'ᱥᱟᱱᱛᱟᱲᱤ', value: 'sat', englishName: 'Santali (Ol Chiki)' },
    { name: 'Gàidhlig', value: 'gd', englishName: 'Scots Gaelic' },
    { name: 'Sepedi', value: 'nso', englishName: 'Sepedi' },
    { name: 'Српски', value: 'sr', englishName: 'Serbian' },
    { name: 'Sesotho', value: 'st', englishName: 'Sesotho' },
    { name: 'Kreol Seselwa', value: 'crs', englishName: 'Seychellois Creole' },
    { name: 'လိၵ်ႈတႆး', value: 'shn', englishName: 'Shan' },
    { name: 'chiShona', value: 'sn', englishName: 'Shona' },
    { name: 'Sicilianu', value: 'scn', englishName: 'Sicilian' },
    { name: 'Ślōnski', value: 'szl', englishName: 'Silesian' },
    { name: 'سنڌي', value: 'sd', englishName: 'Sindhi' },
    { name: 'සිංහල', value: 'si', englishName: 'Sinhala' },
    { name: 'Slovenčina', value: 'sk', englishName: 'Slovak' },
    { name: 'Slovenščina', value: 'sl', englishName: 'Slovenian' },
    { name: 'Soomaali', value: 'so', englishName: 'Somali' },
    { name: 'Español', value: 'es', englishName: 'Spanish' },
    { name: 'Español (España)', value: 'es-ES', englishName: 'Spanish (Spain)' },
    { name: 'Español (Estados Unidos)', value: 'es-US', englishName: 'Spanish (United States)' },
    { name: 'Basa Sunda', value: 'su', englishName: 'Sundanese' },
    { name: 'Surigaonon', value: 'sgd', englishName: 'Surigaonon' },
    { name: 'Susu', value: 'sus', englishName: 'Susu' },
    { name: 'Kiswahili', value: 'sw', englishName: 'Swahili' },
    { name: 'siSwati', value: 'ss', englishName: 'Swati' },
    { name: 'Svenska', value: 'sv', englishName: 'Swedish' },
    { name: 'Tagalog', value: 'tl', englishName: 'Tagalog' },
    { name: 'Reo Tahiti', value: 'ty', englishName: 'Tahitian' },
    { name: 'Тоҷикӣ', value: 'tg', englishName: 'Tajik' },
    { name: 'ⵜⴰⵎⴰⵣⵉⵖⵜ', value: 'zgh', englishName: 'Tamazight' },
    { name: 'ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵜⵉⴼⵉⵏⴰⵖ)', value: 'ber', englishName: 'Tamazight (Tifinagh)' },
    { name: 'தமிழ்', value: 'ta', englishName: 'Tamil' },
    { name: 'Татарча', value: 'tt', englishName: 'Tatar' },
    { name: 'Tausug', value: 'tsg', englishName: 'Tausug' },
    { name: 'తెలుగు', value: 'te', englishName: 'Telugu' },
    { name: 'Tetun', value: 'tet', englishName: 'Tetum' },
    { name: 'ไทย', value: 'th', englishName: 'Thai' },
    { name: 'བོད་སྐད', value: 'bo', englishName: 'Tibetan' },
    { name: 'ትግርኛ', value: 'ti', englishName: 'Tigrinya' },
    { name: 'Tiv', value: 'tiv', englishName: 'Tiv' },
    { name: 'Tok Pisin', value: 'tpi', englishName: 'Tok Pisin' },
    { name: 'Lea Fakatonga', value: 'to', englishName: 'Tongan' },
    { name: 'Tshiluba', value: 'lua', englishName: 'Tshiluba' },
    { name: 'Xitsonga', value: 'ts', englishName: 'Tsonga' },
    { name: 'Setswana', value: 'tn', englishName: 'Tswana' },
    { name: 'ತುಳು', value: 'tcy', englishName: 'Tulu' },
    { name: 'Chitumbuka', value: 'tum', englishName: 'Tumbuka' },
    { name: 'Türkçe', value: 'tr', englishName: 'Turkish' },
    { name: 'Türkmençe', value: 'tk', englishName: 'Turkmen' },
    { name: 'Тыва дыл', value: 'tyv', englishName: 'Tuvan' },
    { name: 'Twi', value: 'tw', englishName: 'Twi' },
    { name: 'Удмурт', value: 'udm', englishName: 'Udmurt' },
    { name: 'Українська', value: 'uk', englishName: 'Ukrainian' },
    { name: 'اردو', value: 'ur', englishName: 'Urdu' },
    { name: 'ئۇيغۇرچە', value: 'ug', englishName: 'Uyghur' },
    { name: 'Oʻzbek', value: 'uz', englishName: 'Uzbek' },
    { name: 'Tshivenḓa', value: 've', englishName: 'Venda' },
    { name: 'Vèneto', value: 'vec', englishName: 'Venetian' },
    { name: 'Tiếng Việt', value: 'vi', englishName: 'Vietnamese' },
    { name: 'Waray', value: 'war', englishName: 'Waray' },
    { name: 'Cymraeg', value: 'cy', englishName: 'Welsh' },
    { name: 'Wolof', value: 'wo', englishName: 'Wolof' },
    { name: 'isiXhosa', value: 'xh', englishName: 'Xhosa' },
    { name: 'Саха тыла', value: 'sah', englishName: 'Yakut' },
    { name: 'ייִדיש', value: 'yi', englishName: 'Yiddish' },
    { name: 'Yorùbá', value: 'yo', englishName: 'Yoruba' },
    { name: 'Yucatec Maya', value: 'yua', englishName: 'Yucatec Maya' },
    { name: 'Zapoteco', value: 'zap', englishName: 'Zapotec' },
    { name: 'Zeêuws', value: 'zea', englishName: 'Zeelandic' },
    { name: 'isiZulu', value: 'zu', englishName: 'Zulu' },
  ];

  private static readonly VOICES: VoiceOption[] = [
    { name: 'Aoede', value: 'Aoede' },
    { name: 'Puck', value: 'Puck' },
    { name: 'Charon', value: 'Charon' },
    { name: 'Kore', value: 'Kore' },
    { name: 'Fenrir', value: 'Fenrir' },
    { name: 'Leda', value: 'Leda' },
    { name: 'Orus', value: 'Orus' },
    { name: 'Zephyr', value: 'Zephyr' },
    { name: 'Achird', value: 'Achird' },
    { name: 'Algenib', value: 'Algenib' },
    { name: 'Algieba', value: 'Algieba' },
    { name: 'Alnilam', value: 'Alnilam' },
    { name: 'Autonoe', value: 'Autonoe' },
    { name: 'Callirrhoe', value: 'Callirrhoe' },
    { name: 'Despina', value: 'Despina' },
    { name: 'Enceladus', value: 'Enceladus' },
    { name: 'Erinome', value: 'Erinome' },
    { name: 'Gacrux', value: 'Gacrux' },
    { name: 'Iapetus', value: 'Iapetus' },
    { name: 'Laomedeia', value: 'Laomedeia' },
    { name: 'Pulcherrima', value: 'Pulcherrima' },
    { name: 'Rasalgethi', value: 'Rasalgethi' },
    { name: 'Sadachbia', value: 'Sadachbia' },
    { name: 'Sadaltager', value: 'Sadaltager' },
    { name: 'Schedar', value: 'Schedar' },
    { name: 'Sulafat', value: 'Sulafat' },
    { name: 'Umbriel', value: 'Umbriel' },
    { name: 'Vindemiatrix', value: 'Vindemiatrix' },
    { name: 'Zubenelgenubi', value: 'Zubenelgenubi' },
    { name: 'Achernar', value: 'Achernar' },
  ];

  private static readonly MODELS: ModelOption[] = [
    { id: 'gemini-2.0-flash-live-001', type: 'realtime' },
    { id: 'gemini-2.5-flash-preview-native-audio-dialog', type: 'realtime' },
  ];

  getConfig(): ProviderConfig {
    return {
      id: 'gemini',
      displayName: 'Gemini',
      
      apiKeyLabel: 'Gemini API Key',
      apiKeyPlaceholder: 'Enter your Gemini API key',
      
      languages: GeminiProviderConfig.LANGUAGES,
      voices: GeminiProviderConfig.VOICES,
      models: GeminiProviderConfig.MODELS,
      noiseReductionModes: [], // Gemini doesn't support noise reduction
      transcriptModels: [], // Gemini uses built-in transcription
      
      capabilities: {
        hasTemplateMode: true,
        hasTurnDetection: false, // Gemini handles turn detection automatically
        hasVoiceSettings: true,
        hasNoiseReduction: false,
        hasModelConfiguration: true, // Gemini supports temperature and max tokens configuration
        
        turnDetection: {
          modes: [], // Gemini handles this automatically
          hasThreshold: false,
          hasPrefixPadding: false,
          hasSilenceDuration: false,
          hasSemanticEagerness: false,
        },
        
        temperatureRange: { min: 0.0, max: 2.0, step: 0.1 },
        maxTokensRange: { min: 1, max: 8192, step: 1 },
      },
      
      defaults: {
        model: 'gemini-2.0-flash-live-001',
        voice: 'Aoede',
        temperature: 1.0,
        maxTokens: 'inf' as any,
        sourceLanguage: 'en-US',
        targetLanguage: 'ja-JP',
        turnDetectionMode: 'Auto', // Gemini handles automatically
        threshold: 0.5,
        prefixPadding: 0.0,
        silenceDuration: 0.0,
        semanticEagerness: 'Auto',
        noiseReduction: 'None',
        transcriptModel: 'auto', // Gemini uses built-in transcription
      },
    };
  }
} 