/**
 * Model Manifest — Single source of truth for all local inference models.
 *
 * All model metadata (identity, languages, download info, file lists) lives here.
 * Engines, stores, and UI all read from this manifest.
 */

// ─── Types ───────────────────────────────────────────────────────────────────

export interface ModelFileEntry {
  /** Filename within the model directory (e.g. 'sherpa-onnx-wasm-main-vad-asr.wasm') */
  filename: string;
  /** File size in bytes */
  sizeBytes: number;
}

export type ModelType = 'asr' | 'asr-stream' | 'tts' | 'translation';
export type ModelStatus = 'not_downloaded' | 'downloading' | 'downloaded' | 'error';
export type TtsEngineType = 'piper' | 'coqui' | 'mimic3' | 'mms' | 'matcha' | 'kokoro' | 'vits';

/** Engine-specific config fields for TTS models (matcha, kokoro, vits special). */
export interface TtsModelConfig {
  acousticModel?: string;  // matcha: e.g. './model-steps-3.onnx'
  vocoder?: string;        // matcha: e.g. './vocos-22khz-univ.onnx'
  lexicon?: string;        // matcha/kokoro/vits: e.g. './lexicon.txt'
  dataDir?: string;        // override engine default: './espeak-ng-data' or ''
  dictDir?: string;        // vits: e.g. './dict'
  ruleFsts?: string;       // comma-separated FST paths
  ruleFars?: string;       // comma-separated FAR paths
}

export interface ModelManifestEntry {
  /** Unique model identifier (e.g. 'sensevoice', 'piper-en', 'opus-mt-ja-en') */
  id: string;
  type: ModelType;
  /** Human-readable name */
  name: string;
  /** Languages supported by this model */
  languages: string[];
  /** Total download size in MB (approximate) */
  totalSizeMb: number;

  // ─── sherpa-onnx specific (ASR / TTS) ──────────────────────────────────
  /** List of files that must be downloaded */
  files?: ModelFileEntry[];
  /** CDN path segment for download URL construction (e.g. 'sherpa-onnx-asr-sensevoice') */
  cdnPath?: string;
  /** TTS .onnx model filename */
  modelFile?: string;
  /** TTS engine type — determines how the worker builds the sherpa-onnx config */
  engine?: TtsEngineType;
  /** Engine-specific config for matcha/kokoro/vits models */
  ttsConfig?: TtsModelConfig;

  // ─── Translation specific ──────────────────────────────────────────────
  /** HuggingFace model ID (e.g. 'Xenova/opus-mt-ja-en') */
  hfModelId?: string;
  sourceLang?: string;
  targetLang?: string;
}

// ─── CDN URL Configuration ───────────────────────────────────────────────────

/**
 * Base URL for ASR/translation model file downloads.
 * - Development: Vite dev server serves from public/wasm/ (default)
 * - Production: Set VITE_MODEL_CDN_URL env var to a CDN endpoint
 */
export function getModelCdnBaseUrl(): string {
  return (import.meta as any).env?.VITE_MODEL_CDN_URL || '/wasm';
}

/**
 * Base URL for TTS model data file downloads.
 * - Development: Vite dev server serves from public/model-packs/tts/ (default)
 * - Production: Set VITE_TTS_CDN_URL env var (e.g. HuggingFace dataset URL)
 */
export function getTtsCdnBaseUrl(): string {
  return (import.meta as any).env?.VITE_TTS_CDN_URL || '/model-packs/tts';
}

/**
 * Get the download URL for a specific file within a model.
 */
export function getModelFileUrl(cdnPath: string, filename: string, type?: ModelType): string {
  const base = type === 'tts' ? getTtsCdnBaseUrl() : getModelCdnBaseUrl();
  return `${base}/${cdnPath}/${filename}`;
}

/**
 * Base path for bundled TTS runtime files (JS/WASM shared across all models).
 * These are shipped with the app at build time to avoid Chrome extension
 * restrictions on downloading and executing JS/WASM at runtime.
 */
export const TTS_BUNDLED_RUNTIME_PATH = '/wasm/sherpa-onnx-tts';

// ─── Shared File Lists ───────────────────────────────────────────────────────
// Offline VAD+ASR models share the same WASM binary structure (same .js/.wasm
// filenames) with different .data files containing different models.
// Sizes are from sensevoice; other models have similar .js/.wasm but different .data.

const ASR_FILES: ModelFileEntry[] = [
  { filename: 'sherpa-onnx-wasm-main-vad-asr.js', sizeBytes: 95_318 },
  { filename: 'sherpa-onnx-wasm-main-vad-asr.wasm', sizeBytes: 11_700_583 },
  { filename: 'sherpa-onnx-wasm-main-vad-asr.data', sizeBytes: 240_193_589 },
  { filename: 'sherpa-onnx-vad.js', sizeBytes: 7_764 },
  { filename: 'sherpa-onnx-asr.js', sizeBytes: 46_198 },
];

// Streaming ASR models use a different WASM binary (no VAD, different main file names).
// Sizes are from stream-en; other streaming models have different .data sizes.
const STREAM_ASR_FILES: ModelFileEntry[] = [
  { filename: 'sherpa-onnx-wasm-main-asr.js', sizeBytes: 92_240 },
  { filename: 'sherpa-onnx-wasm-main-asr.wasm', sizeBytes: 11_547_795 },
  { filename: 'sherpa-onnx-wasm-main-asr.data', sizeBytes: 190_951_044 },
  { filename: 'sherpa-onnx-asr.js', sizeBytes: 46_198 },
];

// TTS runtime JS/WASM are bundled with the app at /wasm/sherpa-onnx-tts/
// (identical across all 387 models). Only model-specific files need downloading.
const TTS_FILES: ModelFileEntry[] = [
  { filename: 'sherpa-onnx-wasm-main-tts.data', sizeBytes: 0 },        // varies per model
  { filename: 'package-metadata.json', sizeBytes: 0 },                  // ~27KB, Emscripten FS layout
];

// Translation models (Opus-MT via Transformers.js) share the same file structure.
// Sizes are from Xenova/opus-mt-ja-en; other pairs are similar.
const TRANSLATION_FILES: ModelFileEntry[] = [
  { filename: 'config.json', sizeBytes: 1_376 },
  { filename: 'generation_config.json', sizeBytes: 293 },
  { filename: 'tokenizer.json', sizeBytes: 5_991_485 },
  { filename: 'tokenizer_config.json', sizeBytes: 280 },
  { filename: 'onnx/encoder_model_quantized.onnx', sizeBytes: 50_705_822 },
  { filename: 'onnx/decoder_model_merged_quantized.onnx', sizeBytes: 58_001_744 },
];

// ─── Model Manifest ──────────────────────────────────────────────────────────

export const MODEL_MANIFEST: ModelManifestEntry[] = [

  // ── Offline VAD+ASR Models ─────────────────────────────────────────────
  {
    id: 'sensevoice',
    type: 'asr',
    name: 'SenseVoice (ja/zh/en/ko/cantonese)',
    languages: ['ja', 'zh', 'en', 'ko', 'cantonese'],
    totalSizeMb: 158,
    cdnPath: 'sherpa-onnx-asr-sensevoice',
    files: ASR_FILES,
  },
  {
    id: 'reazonspeech',
    type: 'asr',
    name: 'ReazonSpeech (Japanese only)',
    languages: ['ja'],
    totalSizeMb: 137,
    cdnPath: 'sherpa-onnx-asr-reazonspeech',
    files: ASR_FILES,
  },
  {
    id: 'whisper-en',
    type: 'asr',
    name: 'Whisper Tiny (English)',
    languages: ['en'],
    totalSizeMb: 51,
    cdnPath: 'sherpa-onnx-asr-whisper-en',
    files: ASR_FILES,
  },
  {
    id: 'zipformer-en',
    type: 'asr',
    name: 'Zipformer GigaSpeech (English)',
    languages: ['en'],
    totalSizeMb: 59,
    cdnPath: 'sherpa-onnx-asr-zipformer-en',
    files: ASR_FILES,
  },
  {
    id: 'moonshine-en',
    type: 'asr',
    name: 'Moonshine Tiny (English)',
    languages: ['en'],
    totalSizeMb: 105,
    cdnPath: 'sherpa-onnx-asr-moonshine-en',
    files: ASR_FILES,
  },
  {
    id: 'paraformer-small',
    type: 'asr',
    name: 'Paraformer Small (zh/en)',
    languages: ['zh', 'en'],
    totalSizeMb: 77,
    cdnPath: 'sherpa-onnx-asr-paraformer-small',
    files: ASR_FILES,
  },
  {
    id: 'paraformer-large',
    type: 'asr',
    name: 'Paraformer Large (zh/en)',
    languages: ['zh', 'en'],
    totalSizeMb: 225,
    cdnPath: 'sherpa-onnx-asr-paraformer-large',
    files: ASR_FILES,
  },
  {
    id: 'wenetspeech',
    type: 'asr',
    name: 'Zipformer WenetSpeech (Chinese)',
    languages: ['zh'],
    totalSizeMb: 69,
    cdnPath: 'sherpa-onnx-asr-wenetspeech',
    files: ASR_FILES,
  },
  {
    id: 'telespeech',
    type: 'asr',
    name: 'TeleSpeech (Chinese)',
    languages: ['zh'],
    totalSizeMb: 177,
    cdnPath: 'sherpa-onnx-asr-telespeech',
    files: ASR_FILES,
  },
  {
    id: 'zipformer-ctc-zh',
    type: 'asr',
    name: 'Zipformer CTC (Chinese)',
    languages: ['zh'],
    totalSizeMb: 290,
    cdnPath: 'sherpa-onnx-asr-zipformer-ctc-zh',
    files: ASR_FILES,
  },
  {
    id: 'dolphin',
    type: 'asr',
    name: 'Dolphin CTC (multilingual)',
    languages: ['zh', 'en', 'ja', 'ko', 'de', 'fr', 'es'],
    totalSizeMb: 80,
    cdnPath: 'sherpa-onnx-asr-dolphin',
    files: ASR_FILES,
  },
  {
    id: 'gigaspeech2-th',
    type: 'asr',
    name: 'Zipformer GigaSpeech2 (Thai)',
    languages: ['th'],
    totalSizeMb: 126,
    cdnPath: 'sherpa-onnx-asr-gigaspeech2-th',
    files: ASR_FILES,
  },

  // ── Streaming ASR Models ───────────────────────────────────────────────
  // These use a different WASM binary (no VAD) and require a streaming engine.
  {
    id: 'stream-en',
    type: 'asr-stream',
    name: 'Streaming Zipformer (English)',
    languages: ['en'],
    totalSizeMb: 167,
    cdnPath: 'sherpa-onnx-asr-stream-en',
    files: STREAM_ASR_FILES,
  },
  {
    id: 'stream-zh-en',
    type: 'asr-stream',
    name: 'Streaming Zipformer (zh/en)',
    languages: ['zh', 'en'],
    totalSizeMb: 173,
    cdnPath: 'sherpa-onnx-asr-stream-zh-en',
    files: STREAM_ASR_FILES,
  },
  {
    id: 'stream-paraformer',
    type: 'asr-stream',
    name: 'Streaming Paraformer (zh/en)',
    languages: ['zh', 'en'],
    totalSizeMb: 218,
    cdnPath: 'sherpa-onnx-asr-stream-paraformer',
    files: STREAM_ASR_FILES,
  },
  {
    id: 'stream-paraformer-cantonese',
    type: 'asr-stream',
    name: 'Streaming Paraformer (zh/cantonese/en)',
    languages: ['zh', 'cantonese', 'en'],
    totalSizeMb: 219,
    cdnPath: 'sherpa-onnx-asr-stream-paraformer-cantonese',
    files: STREAM_ASR_FILES,
  },

  // ── TTS Models ─────────────────────────────────────────────────────────
  // 136 models across 53 languages, selected by speed benchmark.
  // Per language+gender: top 2 fastest, plus similar-speed Piper speakers.
  {
    id: 'mimic3-af-google_nwu-low',
    type: 'tts',
    name: 'Mimic3 (Afrikaans)',
    languages: ['af'],
    totalSizeMb: 102,
    cdnPath: 'wasm-mimic3-af-google_nwu-low',
    modelFile: 'af_ZA-google-nwu_low.onnx',
    engine: 'mimic3',
    files: TTS_FILES,
  },
  {
    id: 'piper-ar-kareem-low',
    type: 'tts',
    name: 'Piper Kareem Low (Arabic, male)',
    languages: ['ar'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-ar-kareem-low',
    modelFile: 'ar_JO-kareem-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-ar-kareem-medium',
    type: 'tts',
    name: 'Piper Kareem Medium (Arabic, male)',
    languages: ['ar'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-ar-kareem-medium',
    modelFile: 'ar_JO-kareem-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'coqui-bg-cv',
    type: 'tts',
    name: 'Coqui (Bulgarian)',
    languages: ['bg'],
    totalSizeMb: 79,
    cdnPath: 'wasm-coqui-bg-cv',
    engine: 'coqui',
    files: TTS_FILES,
  },
  {
    id: 'mimic3-bn-multi-low',
    type: 'tts',
    name: 'Mimic3 (Bengali, multi-speaker)',
    languages: ['bn'],
    totalSizeMb: 102,
    cdnPath: 'wasm-mimic3-bn-multi-low',
    modelFile: 'bn-multi_low.onnx',
    engine: 'mimic3',
    files: TTS_FILES,
  },
  {
    id: 'coqui-bn-custom_female',
    type: 'tts',
    name: 'Coqui (Bengali, female)',
    languages: ['bn'],
    totalSizeMb: 121,
    cdnPath: 'wasm-coqui-bn-custom_female',
    engine: 'coqui',
    files: TTS_FILES,
  },
  {
    id: 'piper-ca-upc_pau-x_low',
    type: 'tts',
    name: 'Piper Upc pau X low (Catalan, male)',
    languages: ['ca'],
    totalSizeMb: 48,
    cdnPath: 'wasm-piper-ca-upc_pau-x_low',
    modelFile: 'ca_ES-upc_pau-x_low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-ca-upc_ona-x_low',
    type: 'tts',
    name: 'Piper Upc ona X low (Catalan, female)',
    languages: ['ca'],
    totalSizeMb: 48,
    cdnPath: 'wasm-piper-ca-upc_ona-x_low',
    modelFile: 'ca_ES-upc_ona-x_low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-ca-upc_ona-medium',
    type: 'tts',
    name: 'Piper Upc ona Medium (Catalan, female)',
    languages: ['ca'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-ca-upc_ona-medium',
    modelFile: 'ca_ES-upc_ona-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-cs-jirka-low',
    type: 'tts',
    name: 'Piper Jirka Low (Czech, male)',
    languages: ['cs'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-cs-jirka-low',
    modelFile: 'cs_CZ-jirka-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-cs-jirka-medium',
    type: 'tts',
    name: 'Piper Jirka Medium (Czech, male)',
    languages: ['cs'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-cs-jirka-medium',
    modelFile: 'cs_CZ-jirka-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-cy-gwryw_gogleddol-medium',
    type: 'tts',
    name: 'Piper Gwryw gogleddol Medium (Welsh, male)',
    languages: ['cy'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-cy-gwryw_gogleddol-medium',
    modelFile: 'cy_GB-gwryw_gogleddol-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-cy-bu_tts-medium',
    type: 'tts',
    name: 'Piper Bu tts Medium (Welsh, multi-speaker)',
    languages: ['cy'],
    totalSizeMb: 102,
    cdnPath: 'wasm-piper-cy-bu_tts-medium',
    modelFile: 'cy_GB-bu_tts-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-da-talesyntese-medium',
    type: 'tts',
    name: 'Piper Talesyntese Medium (Danish, female)',
    languages: ['da'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-da-talesyntese-medium',
    modelFile: 'da_DK-talesyntese-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-de-eva_k-x_low',
    type: 'tts',
    name: 'Piper Eva k X low (German, female)',
    languages: ['de'],
    totalSizeMb: 48,
    cdnPath: 'wasm-piper-de-eva_k-x_low',
    modelFile: 'de_DE-eva_k-x_low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-de-glados-low',
    type: 'tts',
    name: 'Piper Glados Low (German, female)',
    languages: ['de'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-de-glados-low',
    modelFile: 'de_DE-glados-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-de-glados_turret-low',
    type: 'tts',
    name: 'Piper Glados turret Low (German, female)',
    languages: ['de'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-de-glados_turret-low',
    modelFile: 'de_DE-glados_turret-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-de-ramona-low',
    type: 'tts',
    name: 'Piper Ramona Low (German, female)',
    languages: ['de'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-de-ramona-low',
    modelFile: 'de_DE-ramona-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-de-thorsten-low',
    type: 'tts',
    name: 'Piper Thorsten Low (German, male)',
    languages: ['de'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-de-thorsten-low',
    modelFile: 'de_DE-thorsten-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-de-pavoque-low',
    type: 'tts',
    name: 'Piper Pavoque Low (German, male)',
    languages: ['de'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-de-pavoque-low',
    modelFile: 'de_DE-pavoque-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-de-kerstin-low',
    type: 'tts',
    name: 'Piper Kerstin Low (German, female)',
    languages: ['de'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-de-kerstin-low',
    modelFile: 'de_DE-kerstin-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-de-karlsson-low',
    type: 'tts',
    name: 'Piper Karlsson Low (German, male)',
    languages: ['de'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-de-karlsson-low',
    modelFile: 'de_DE-karlsson-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-el-rapunzelina-low',
    type: 'tts',
    name: 'Piper Rapunzelina Low (Greek, female)',
    languages: ['el'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-el-rapunzelina-low',
    modelFile: 'el_GR-rapunzelina-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'mimic3-el-rapunzelina-low',
    type: 'tts',
    name: 'Mimic3 (Greek, female)',
    languages: ['el'],
    totalSizeMb: 89,
    cdnPath: 'wasm-mimic3-el-rapunzelina-low',
    modelFile: 'el_GR-rapunzelina_low.onnx',
    engine: 'mimic3',
    files: TTS_FILES,
  },
  {
    id: 'piper-en-amy-low',
    type: 'tts',
    name: 'Piper Amy Low (English, female)',
    languages: ['en'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-en-amy-low',
    modelFile: 'en_US-amy-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-en-gb-alan-low',
    type: 'tts',
    name: 'Piper Alan Low (English, male)',
    languages: ['en'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-en-gb-alan-low',
    modelFile: 'en_GB-alan-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-en-gb-south-female-low',
    type: 'tts',
    name: 'Piper South Female Low (English, female)',
    languages: ['en'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-en-gb-south-female-low',
    modelFile: 'en_GB-southern_english_female-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-en-kathleen-low',
    type: 'tts',
    name: 'Piper Kathleen Low (English, female)',
    languages: ['en'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-en-kathleen-low',
    modelFile: 'en_US-kathleen-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-en-lessac-low',
    type: 'tts',
    name: 'Piper Lessac Low (English, male)',
    languages: ['en'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-en-lessac-low',
    modelFile: 'en_US-lessac-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-en-ryan-low',
    type: 'tts',
    name: 'Piper Ryan Low (English, male)',
    languages: ['en'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-en-ryan-low',
    modelFile: 'en_US-ryan-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-en-danny-low',
    type: 'tts',
    name: 'Piper Danny Low (English, male)',
    languages: ['en'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-en-danny-low',
    modelFile: 'en_US-danny-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-en-arctic-medium',
    type: 'tts',
    name: 'Piper Arctic Medium (English, multi-speaker)',
    languages: ['en'],
    totalSizeMb: 102,
    cdnPath: 'wasm-piper-en-arctic-medium',
    modelFile: 'en_US-arctic-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-en-libritts_r-medium',
    type: 'tts',
    name: 'Piper Libritts r Medium (English, multi-speaker)',
    languages: ['en'],
    totalSizeMb: 104,
    cdnPath: 'wasm-piper-en-libritts_r-medium',
    modelFile: 'en_US-libritts_r-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-en-gb-vctk-medium',
    type: 'tts',
    name: 'Piper Vctk Medium (English, multi-speaker)',
    languages: ['en'],
    totalSizeMb: 102,
    cdnPath: 'wasm-piper-en-gb-vctk-medium',
    modelFile: 'en_GB-vctk-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-en-gb-semaine-medium',
    type: 'tts',
    name: 'Piper Semaine Medium (English, multi-speaker)',
    languages: ['en'],
    totalSizeMb: 102,
    cdnPath: 'wasm-piper-en-gb-semaine-medium',
    modelFile: 'en_GB-semaine-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-en-l2arctic-medium',
    type: 'tts',
    name: 'Piper L2arctic Medium (English, multi-speaker)',
    languages: ['en'],
    totalSizeMb: 102,
    cdnPath: 'wasm-piper-en-l2arctic-medium',
    modelFile: 'en_US-l2arctic-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-en-gb-aru-medium',
    type: 'tts',
    name: 'Piper Aru Medium (English, multi-speaker)',
    languages: ['en'],
    totalSizeMb: 102,
    cdnPath: 'wasm-piper-en-gb-aru-medium',
    modelFile: 'en_GB-aru-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-es-carlfm-x_low',
    type: 'tts',
    name: 'Piper Carlfm X low (Spanish, male)',
    languages: ['es'],
    totalSizeMb: 48,
    cdnPath: 'wasm-piper-es-carlfm-x_low',
    modelFile: 'es_ES-carlfm-x_low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-es-glados-medium',
    type: 'tts',
    name: 'Piper Glados Medium (Spanish, female)',
    languages: ['es'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-es-glados-medium',
    modelFile: 'es_ES-glados-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-es-mx-claude-high',
    type: 'tts',
    name: 'Piper Claude High (Spanish, male)',
    languages: ['es'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-es-mx-claude-high',
    modelFile: 'es_MX-claude-high.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-es-mx-ald-medium',
    type: 'tts',
    name: 'Piper Ald Medium (Spanish, female)',
    languages: ['es'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-es-mx-ald-medium',
    modelFile: 'es_MX-ald-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-es-sharvard-medium',
    type: 'tts',
    name: 'Piper Sharvard Medium (Spanish, multi-speaker)',
    languages: ['es'],
    totalSizeMb: 102,
    cdnPath: 'wasm-piper-es-sharvard-medium',
    modelFile: 'es_ES-sharvard-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-es-davefx-medium',
    type: 'tts',
    name: 'Piper Davefx Medium (Spanish, male)',
    languages: ['es'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-es-davefx-medium',
    modelFile: 'es_ES-davefx-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'coqui-et-cv',
    type: 'tts',
    name: 'Coqui (Estonian)',
    languages: ['et'],
    totalSizeMb: 79,
    cdnPath: 'wasm-coqui-et-cv',
    engine: 'coqui',
    files: TTS_FILES,
  },
  {
    id: 'piper-fa-reza-medium',
    type: 'tts',
    name: 'Piper Reza Medium (Farsi, male)',
    languages: ['fa'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-fa-reza-medium',
    modelFile: 'fa_IR-reza_ibrahim-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'mimic3-fa-haaniye-low',
    type: 'tts',
    name: 'Mimic3 (Farsi, female)',
    languages: ['fa'],
    totalSizeMb: 89,
    cdnPath: 'wasm-mimic3-fa-haaniye-low',
    modelFile: 'fa-haaniye_low.onnx',
    engine: 'mimic3',
    files: TTS_FILES,
  },
  {
    id: 'piper-fa-en-rezahedayatfar-ibrahimwalk-medium',
    type: 'tts',
    name: 'Piper Rezahedayatfar Ibrahimwalk Medium (Farsi, male)',
    languages: ['fa', 'en'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-fa-en-rezahedayatfar-ibrahimwalk-medium',
    modelFile: 'fa_en-rezahedayatfar-ibrahimwalk-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-fa-ganji_adabi-medium',
    type: 'tts',
    name: 'Piper Ganji adabi Medium (Farsi, male)',
    languages: ['fa'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-fa-ganji_adabi-medium',
    modelFile: 'fa_IR-ganji_adabi-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-fa-amir-medium',
    type: 'tts',
    name: 'Piper Amir Medium (Farsi, male)',
    languages: ['fa'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-fa-amir-medium',
    modelFile: 'fa_IR-amir-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-fa-gyro-medium',
    type: 'tts',
    name: 'Piper Gyro Medium (Farsi, male)',
    languages: ['fa'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-fa-gyro-medium',
    modelFile: 'fa_IR-gyro-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-fa-ganji-medium',
    type: 'tts',
    name: 'Piper Ganji Medium (Farsi, male)',
    languages: ['fa'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-fa-ganji-medium',
    modelFile: 'fa_IR-ganji-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'matcha-fa-en-khadijah',
    type: 'tts',
    name: 'Matcha (Farsi, female)',
    languages: ['fa', 'en'],
    totalSizeMb: 151,
    cdnPath: 'wasm-matcha-fa-en-khadijah',
    engine: 'matcha',
    ttsConfig: {
      acousticModel: './model.onnx',
      vocoder: './vocos-22khz-univ.onnx',
      dataDir: './espeak-ng-data',
    },
    files: TTS_FILES,
  },
  {
    id: 'piper-fi-harri-low',
    type: 'tts',
    name: 'Piper Harri Low (Finnish, male)',
    languages: ['fi'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-fi-harri-low',
    modelFile: 'fi_FI-harri-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-fi-harri-medium',
    type: 'tts',
    name: 'Piper Harri Medium (Finnish, male)',
    languages: ['fi'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-fi-harri-medium',
    modelFile: 'fi_FI-harri-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-fr-siwis-low',
    type: 'tts',
    name: 'Piper Siwis Low (French, female)',
    languages: ['fr'],
    totalSizeMb: 48,
    cdnPath: 'wasm-piper-fr-siwis-low',
    modelFile: 'fr_FR-siwis-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-fr-gilles-low',
    type: 'tts',
    name: 'Piper Gilles Low (French, male)',
    languages: ['fr'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-fr-gilles-low',
    modelFile: 'fr_FR-gilles-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-fr-siwis-medium',
    type: 'tts',
    name: 'Piper Siwis Medium (French, female)',
    languages: ['fr'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-fr-siwis-medium',
    modelFile: 'fr_FR-siwis-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-fr-upmc-medium',
    type: 'tts',
    name: 'Piper Upmc Medium (French, multi-speaker)',
    languages: ['fr'],
    totalSizeMb: 102,
    cdnPath: 'wasm-piper-fr-upmc-medium',
    modelFile: 'fr_FR-upmc-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-fr-tjiho3-medium',
    type: 'tts',
    name: 'Piper Tjiho3 Medium (French, male)',
    languages: ['fr'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-fr-tjiho3-medium',
    modelFile: 'fr_FR-tjiho-model3.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-fr-tom-medium',
    type: 'tts',
    name: 'Piper Tom Medium (French, male)',
    languages: ['fr'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-fr-tom-medium',
    modelFile: 'fr_FR-tom-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-fr-tjiho1-medium',
    type: 'tts',
    name: 'Piper Tjiho1 Medium (French, male)',
    languages: ['fr'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-fr-tjiho1-medium',
    modelFile: 'fr_FR-tjiho-model1.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-fr-tjiho2-medium',
    type: 'tts',
    name: 'Piper Tjiho2 Medium (French, male)',
    languages: ['fr'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-fr-tjiho2-medium',
    modelFile: 'fr_FR-tjiho-model2.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'coqui-ga-cv',
    type: 'tts',
    name: 'Coqui (Irish)',
    languages: ['ga'],
    totalSizeMb: 79,
    cdnPath: 'wasm-coqui-ga-cv',
    engine: 'coqui',
    files: TTS_FILES,
  },
  {
    id: 'mimic3-gu-cmu_indic-low',
    type: 'tts',
    name: 'Mimic3 (Gujarati, multi-speaker)',
    languages: ['gu'],
    totalSizeMb: 102,
    cdnPath: 'wasm-mimic3-gu-cmu_indic-low',
    modelFile: 'gu_IN-cmu-indic_low.onnx',
    engine: 'mimic3',
    files: TTS_FILES,
  },
  {
    id: 'piper-hi-priyamvada-medium',
    type: 'tts',
    name: 'Piper Priyamvada Medium (Hindi, female)',
    languages: ['hi'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-hi-priyamvada-medium',
    modelFile: 'hi_IN-priyamvada-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-hi-pratham-medium',
    type: 'tts',
    name: 'Piper Pratham Medium (Hindi, male)',
    languages: ['hi'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-hi-pratham-medium',
    modelFile: 'hi_IN-pratham-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-hi-rohan-medium',
    type: 'tts',
    name: 'Piper Rohan Medium (Hindi, male)',
    languages: ['hi'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-hi-rohan-medium',
    modelFile: 'hi_IN-rohan-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'coqui-hr-cv',
    type: 'tts',
    name: 'Coqui (Croatian)',
    languages: ['hr'],
    totalSizeMb: 79,
    cdnPath: 'wasm-coqui-hr-cv',
    engine: 'coqui',
    files: TTS_FILES,
  },
  {
    id: 'piper-hu-imre-medium',
    type: 'tts',
    name: 'Piper Imre Medium (Hungarian, male)',
    languages: ['hu'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-hu-imre-medium',
    modelFile: 'hu_HU-imre-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-hu-berta-medium',
    type: 'tts',
    name: 'Piper Berta Medium (Hungarian, female)',
    languages: ['hu'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-hu-berta-medium',
    modelFile: 'hu_HU-berta-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-hu-anna-medium',
    type: 'tts',
    name: 'Piper Anna Medium (Hungarian, female)',
    languages: ['hu'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-hu-anna-medium',
    modelFile: 'hu_HU-anna-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-id-news_tts-medium',
    type: 'tts',
    name: 'Piper News tts Medium (Indonesian)',
    languages: ['id'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-id-news_tts-medium',
    modelFile: 'id_ID-news_tts-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-is-salka-medium',
    type: 'tts',
    name: 'Piper Salka Medium (Icelandic, female)',
    languages: ['is'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-is-salka-medium',
    modelFile: 'is_IS-salka-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-is-ugla-medium',
    type: 'tts',
    name: 'Piper Ugla Medium (Icelandic, female)',
    languages: ['is'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-is-ugla-medium',
    modelFile: 'is_IS-ugla-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-is-bui-medium',
    type: 'tts',
    name: 'Piper Bui Medium (Icelandic, male)',
    languages: ['is'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-is-bui-medium',
    modelFile: 'is_IS-bui-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-is-steinn-medium',
    type: 'tts',
    name: 'Piper Steinn Medium (Icelandic, male)',
    languages: ['is'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-is-steinn-medium',
    modelFile: 'is_IS-steinn-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-it-riccardo-x_low',
    type: 'tts',
    name: 'Piper Riccardo X low (Italian, male)',
    languages: ['it'],
    totalSizeMb: 48,
    cdnPath: 'wasm-piper-it-riccardo-x_low',
    modelFile: 'it_IT-riccardo-x_low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-it-paola-medium',
    type: 'tts',
    name: 'Piper Paola Medium (Italian, female)',
    languages: ['it'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-it-paola-medium',
    modelFile: 'it_IT-paola-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-ka-natia-medium',
    type: 'tts',
    name: 'Piper Natia Medium (Georgian, female)',
    languages: ['ka'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-ka-natia-medium',
    modelFile: 'ka_GE-natia-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-kk-iseke-x_low',
    type: 'tts',
    name: 'Piper Iseke X low (Kazakh, male)',
    languages: ['kk'],
    totalSizeMb: 56,
    cdnPath: 'wasm-piper-kk-iseke-x_low',
    modelFile: 'kk_KZ-iseke-x_low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-kk-raya-x_low',
    type: 'tts',
    name: 'Piper Raya X low (Kazakh, female)',
    languages: ['kk'],
    totalSizeMb: 48,
    cdnPath: 'wasm-piper-kk-raya-x_low',
    modelFile: 'kk_KZ-raya-x_low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-kk-issai-high',
    type: 'tts',
    name: 'Piper Issai High (Kazakh, multi-speaker)',
    languages: ['kk'],
    totalSizeMb: 151,
    cdnPath: 'wasm-piper-kk-issai-high',
    modelFile: 'kk_KZ-issai-high.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'mimic3-ko-kss-low',
    type: 'tts',
    name: 'Mimic3 (Korean, female)',
    languages: ['ko'],
    totalSizeMb: 89,
    cdnPath: 'wasm-mimic3-ko-kss-low',
    modelFile: 'ko_KO-kss_low.onnx',
    engine: 'mimic3',
    files: TTS_FILES,
  },
  {
    id: 'piper-lb-marylux-medium',
    type: 'tts',
    name: 'Piper Marylux Medium (Luxembourgish, female)',
    languages: ['lb'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-lb-marylux-medium',
    modelFile: 'lb_LU-marylux-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'coqui-lt-cv',
    type: 'tts',
    name: 'Coqui (Lithuanian)',
    languages: ['lt'],
    totalSizeMb: 79,
    cdnPath: 'wasm-coqui-lt-cv',
    engine: 'coqui',
    files: TTS_FILES,
  },
  {
    id: 'piper-lv-aivars-medium',
    type: 'tts',
    name: 'Piper Aivars Medium (Latvian, male)',
    languages: ['lv'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-lv-aivars-medium',
    modelFile: 'lv_LV-aivars-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-ml-arjun-medium',
    type: 'tts',
    name: 'Piper Arjun Medium (Malayalam, male)',
    languages: ['ml'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-ml-arjun-medium',
    modelFile: 'ml_IN-arjun-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-ml-meera-medium',
    type: 'tts',
    name: 'Piper Meera Medium (Malayalam, female)',
    languages: ['ml'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-ml-meera-medium',
    modelFile: 'ml_IN-meera-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'coqui-mt-cv',
    type: 'tts',
    name: 'Coqui (Maltese)',
    languages: ['mt'],
    totalSizeMb: 79,
    cdnPath: 'wasm-coqui-mt-cv',
    engine: 'coqui',
    files: TTS_FILES,
  },
  {
    id: 'kokoro',
    type: 'tts',
    name: 'Kokoro (Multilingual, multi-speaker)',
    languages: ['multi'],
    totalSizeMb: 192,
    cdnPath: 'wasm-kokoro',
    modelFile: 'model.int8.onnx',
    engine: 'kokoro',
    ttsConfig: {
      lexicon: './lexicon-us-en.txt,./lexicon-zh.txt',
      ruleFsts: './date-zh.fst,./number-zh.fst,./phone-zh.fst',
    },
    files: TTS_FILES,
  },
  {
    id: 'mms-nan',
    type: 'tts',
    name: 'MMS (Min Nan)',
    languages: ['nan'],
    totalSizeMb: 120,
    cdnPath: 'wasm-mms-nan',
    engine: 'mms',
    files: TTS_FILES,
  },
  {
    id: 'piper-ne-google-x_low',
    type: 'tts',
    name: 'Piper Google X low (Nepali, multi-speaker)',
    languages: ['ne'],
    totalSizeMb: 55,
    cdnPath: 'wasm-piper-ne-google-x_low',
    modelFile: 'ne_NP-google-x_low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-ne-google-medium',
    type: 'tts',
    name: 'Piper Google Medium (Nepali, multi-speaker)',
    languages: ['ne'],
    totalSizeMb: 102,
    cdnPath: 'wasm-piper-ne-google-medium',
    modelFile: 'ne_NP-google-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-ne-chitwan-medium',
    type: 'tts',
    name: 'Piper Chitwan Medium (Nepali, male)',
    languages: ['ne'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-ne-chitwan-medium',
    modelFile: 'ne_NP-chitwan-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-nl-be-nathalie-x_low',
    type: 'tts',
    name: 'Piper Nathalie X low (Dutch, female)',
    languages: ['nl'],
    totalSizeMb: 48,
    cdnPath: 'wasm-piper-nl-be-nathalie-x_low',
    modelFile: 'nl_BE-nathalie-x_low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-nl-be-nathalie-medium',
    type: 'tts',
    name: 'Piper Nathalie Medium (Dutch, female)',
    languages: ['nl'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-nl-be-nathalie-medium',
    modelFile: 'nl_BE-nathalie-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-nl-pim-medium',
    type: 'tts',
    name: 'Piper Pim Medium (Dutch, male)',
    languages: ['nl'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-nl-pim-medium',
    modelFile: 'nl_NL-pim-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-nl-ronnie-medium',
    type: 'tts',
    name: 'Piper Ronnie Medium (Dutch, male)',
    languages: ['nl'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-nl-ronnie-medium',
    modelFile: 'nl_NL-ronnie-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-no-talesyntese-medium',
    type: 'tts',
    name: 'Piper Talesyntese Medium (Norwegian)',
    languages: ['no'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-no-talesyntese-medium',
    modelFile: 'no_NO-talesyntese-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-pl-darkman-medium',
    type: 'tts',
    name: 'Piper Darkman Medium (Polish, male)',
    languages: ['pl'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-pl-darkman-medium',
    modelFile: 'pl_PL-darkman-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-pl-gosia-medium',
    type: 'tts',
    name: 'Piper Gosia Medium (Polish, female)',
    languages: ['pl'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-pl-gosia-medium',
    modelFile: 'pl_PL-gosia-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-pl-zenski-medium',
    type: 'tts',
    name: 'Piper Zenski Medium (Polish, female)',
    languages: ['pl'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-pl-zenski-medium',
    modelFile: 'pl_PL-zenski_wg_glos-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-pl-mc_speech-medium',
    type: 'tts',
    name: 'Piper Mc speech Medium (Polish, male)',
    languages: ['pl'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-pl-mc_speech-medium',
    modelFile: 'pl_PL-mc_speech-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-pl-meski-medium',
    type: 'tts',
    name: 'Piper Meski Medium (Polish, male)',
    languages: ['pl'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-pl-meski-medium',
    modelFile: 'pl_PL-meski_wg_glos-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-pl-justyna-medium',
    type: 'tts',
    name: 'Piper Justyna Medium (Polish, female)',
    languages: ['pl'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-pl-justyna-medium',
    modelFile: 'pl_PL-justyna_wg_glos-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-pl-jarvis-medium',
    type: 'tts',
    name: 'Piper Jarvis Medium (Polish, male)',
    languages: ['pl'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-pl-jarvis-medium',
    modelFile: 'pl_PL-jarvis_wg_glos-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-pt-br-edresson-low',
    type: 'tts',
    name: 'Piper Edresson Low (Portuguese, male)',
    languages: ['pt'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-pt-br-edresson-low',
    modelFile: 'pt_BR-edresson-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-pt-br-faber-medium',
    type: 'tts',
    name: 'Piper Faber Medium (Portuguese, male)',
    languages: ['pt'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-pt-br-faber-medium',
    modelFile: 'pt_BR-faber-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-pt-tugao-medium',
    type: 'tts',
    name: 'Piper Tugao Medium (Portuguese, male)',
    languages: ['pt'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-pt-tugao-medium',
    modelFile: 'pt_PT-tugao-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-pt-br-jeff-medium',
    type: 'tts',
    name: 'Piper Jeff Medium (Portuguese, male)',
    languages: ['pt'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-pt-br-jeff-medium',
    modelFile: 'pt_BR-jeff-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-ro-mihai-medium',
    type: 'tts',
    name: 'Piper Mihai Medium (Romanian, male)',
    languages: ['ro'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-ro-mihai-medium',
    modelFile: 'ro_RO-mihai-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-ru-denis-medium',
    type: 'tts',
    name: 'Piper Denis Medium (Russian, male)',
    languages: ['ru'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-ru-denis-medium',
    modelFile: 'ru_RU-denis-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-ru-dmitri-medium',
    type: 'tts',
    name: 'Piper Dmitri Medium (Russian, male)',
    languages: ['ru'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-ru-dmitri-medium',
    modelFile: 'ru_RU-dmitri-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-ru-ruslan-medium',
    type: 'tts',
    name: 'Piper Ruslan Medium (Russian, male)',
    languages: ['ru'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-ru-ruslan-medium',
    modelFile: 'ru_RU-ruslan-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-ru-irina-medium',
    type: 'tts',
    name: 'Piper Irina Medium (Russian, female)',
    languages: ['ru'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-ru-irina-medium',
    modelFile: 'ru_RU-irina-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-sk-lili-medium',
    type: 'tts',
    name: 'Piper Lili Medium (Slovak, female)',
    languages: ['sk'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-sk-lili-medium',
    modelFile: 'sk_SK-lili-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-sl-artur-medium',
    type: 'tts',
    name: 'Piper Artur Medium (Slovenian, male)',
    languages: ['sl'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-sl-artur-medium',
    modelFile: 'sl_SI-artur-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-sr-serbski_institut-medium',
    type: 'tts',
    name: 'Piper Serbski institut Medium (Serbian, multi-speaker)',
    languages: ['sr'],
    totalSizeMb: 102,
    cdnPath: 'wasm-piper-sr-serbski_institut-medium',
    modelFile: 'sr_RS-serbski_institut-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-sv-nst-medium',
    type: 'tts',
    name: 'Piper Nst Medium (Swedish, multi-speaker)',
    languages: ['sv'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-sv-nst-medium',
    modelFile: 'sv_SE-nst-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-sv-lisa-medium',
    type: 'tts',
    name: 'Piper Lisa Medium (Swedish, female)',
    languages: ['sv'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-sv-lisa-medium',
    modelFile: 'sv_SE-lisa-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-sw-lanfrica-medium',
    type: 'tts',
    name: 'Piper Lanfrica Medium (Swahili)',
    languages: ['sw'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-sw-lanfrica-medium',
    modelFile: 'sw_CD-lanfrica-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'mms-tha',
    type: 'tts',
    name: 'MMS (Thai)',
    languages: ['th'],
    totalSizeMb: 120,
    cdnPath: 'wasm-mms-tha',
    engine: 'mms',
    files: TTS_FILES,
  },
  {
    id: 'mimic3-tn-google_nwu-low',
    type: 'tts',
    name: 'Mimic3 (Tswana, multi-speaker)',
    languages: ['tn'],
    totalSizeMb: 102,
    cdnPath: 'wasm-mimic3-tn-google_nwu-low',
    modelFile: 'tn_ZA-google-nwu_low.onnx',
    engine: 'mimic3',
    files: TTS_FILES,
  },
  {
    id: 'piper-tr-fettah-medium',
    type: 'tts',
    name: 'Piper Fettah Medium (Turkish, male)',
    languages: ['tr'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-tr-fettah-medium',
    modelFile: 'tr_TR-fettah-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-tr-dfki-medium',
    type: 'tts',
    name: 'Piper Dfki Medium (Turkish, male)',
    languages: ['tr'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-tr-dfki-medium',
    modelFile: 'tr_TR-dfki-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-tr-fahrettin-medium',
    type: 'tts',
    name: 'Piper Fahrettin Medium (Turkish, male)',
    languages: ['tr'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-tr-fahrettin-medium',
    modelFile: 'tr_TR-fahrettin-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-uk-lada-x_low',
    type: 'tts',
    name: 'Piper Lada X low (Ukrainian, female)',
    languages: ['uk'],
    totalSizeMb: 48,
    cdnPath: 'wasm-piper-uk-lada-x_low',
    modelFile: 'uk_UA-lada-x_low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-uk-ukrainian_tts-medium',
    type: 'tts',
    name: 'Piper Ukrainian tts Medium (Ukrainian, multi-speaker)',
    languages: ['uk'],
    totalSizeMb: 102,
    cdnPath: 'wasm-piper-uk-ukrainian_tts-medium',
    modelFile: 'uk_UA-ukrainian_tts-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-vi-vivos-x_low',
    type: 'tts',
    name: 'Piper Vivos X low (Vietnamese, multi-speaker)',
    languages: ['vi'],
    totalSizeMb: 55,
    cdnPath: 'wasm-piper-vi-vivos-x_low',
    modelFile: 'vi_VN-vivos-x_low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'piper-vi-25hours-low',
    type: 'tts',
    name: 'Piper 25hours Low (Vietnamese, female)',
    languages: ['vi'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-vi-25hours-low',
    modelFile: 'vi_VN-25hours_single-low.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'mimic3-vi-vais1000-low',
    type: 'tts',
    name: 'Mimic3 (Vietnamese, female)',
    languages: ['vi'],
    totalSizeMb: 89,
    cdnPath: 'wasm-mimic3-vi-vais1000-low',
    modelFile: 'vi_VN-vais1000_low.onnx',
    engine: 'mimic3',
    files: TTS_FILES,
  },
  {
    id: 'piper-vi-vais1000-medium',
    type: 'tts',
    name: 'Piper Vais1000 Medium (Vietnamese, female)',
    languages: ['vi'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-vi-vais1000-medium',
    modelFile: 'vi_VN-vais1000-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'cantonese',
    type: 'tts',
    name: 'Cantonese VITS (Cantonese, female)',
    languages: ['yue'],
    totalSizeMb: 121,
    cdnPath: 'wasm-cantonese',
    modelFile: 'vits-cantonese-hf-xiaomaiiwn.onnx',
    engine: 'vits',
    ttsConfig: {
      lexicon: './lexicon.txt',
      ruleFsts: './rule.fst',
    },
    files: TTS_FILES,
  },
  {
    id: 'icefall-zh-aishell3',
    type: 'tts',
    name: 'Icefall AISHELL3 (Chinese, multi-speaker)',
    languages: ['zh'],
    totalSizeMb: 215,
    cdnPath: 'wasm-icefall-zh-aishell3',
    engine: 'vits',
    ttsConfig: {
      lexicon: './lexicon.txt',
      ruleFsts: './date.fst,./number.fst,./phone.fst,./new_heteronym.fst',
      ruleFars: './rule.far',
    },
    files: TTS_FILES,
  },
  {
    id: 'piper-zh-huayan-medium',
    type: 'tts',
    name: 'Piper Huayan Medium (Chinese, female)',
    languages: ['zh'],
    totalSizeMb: 89,
    cdnPath: 'wasm-piper-zh-huayan-medium',
    modelFile: 'zh_CN-huayan-medium.onnx',
    engine: 'piper',
    files: TTS_FILES,
  },
  {
    id: 'matcha-zh-baker',
    type: 'tts',
    name: 'Matcha Baker (Chinese, female)',
    languages: ['zh'],
    totalSizeMb: 150,
    cdnPath: 'wasm-matcha-zh-baker',
    engine: 'matcha',
    ttsConfig: {
      acousticModel: './model-steps-3.onnx',
      vocoder: './vocos-22khz-univ.onnx',
      lexicon: './lexicon.txt',
      ruleFsts: './date.fst,./phone.fst',
    },
    files: TTS_FILES,
  },

  // ── Translation Models ───────────────────────────────────────────────────
  // All translation models use CDN + IndexedDB (same as ASR/TTS).
  // hfModelId is still needed by the worker for pipeline() identification.

  // ── Existing Core Pairs (ja/zh/ko/de/fr/es ↔ en) ──────────────────────
  { id: 'opus-mt-ja-en', type: 'translation', name: 'Opus-MT (ja → en)', languages: ['ja', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-ja-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-ja-en', sourceLang: 'ja', targetLang: 'en' },
  { id: 'opus-mt-en-jap', type: 'translation', name: 'Opus-MT (en → ja)', languages: ['en', 'ja'], totalSizeMb: 110, cdnPath: 'opus-mt-en-jap', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-jap', sourceLang: 'en', targetLang: 'ja' },
  { id: 'opus-mt-zh-en', type: 'translation', name: 'Opus-MT (zh → en)', languages: ['zh', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-zh-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-zh-en', sourceLang: 'zh', targetLang: 'en' },
  { id: 'opus-mt-en-zh', type: 'translation', name: 'Opus-MT (en → zh)', languages: ['en', 'zh'], totalSizeMb: 110, cdnPath: 'opus-mt-en-zh', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-zh', sourceLang: 'en', targetLang: 'zh' },
  { id: 'opus-mt-ko-en', type: 'translation', name: 'Opus-MT (ko → en)', languages: ['ko', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-ko-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-ko-en', sourceLang: 'ko', targetLang: 'en' },
  { id: 'opus-mt-en-ko', type: 'translation', name: 'Opus-MT (en → ko)', languages: ['en', 'ko'], totalSizeMb: 110, cdnPath: 'opus-mt-en-ko', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-ko', sourceLang: 'en', targetLang: 'ko' },
  { id: 'opus-mt-de-en', type: 'translation', name: 'Opus-MT (de → en)', languages: ['de', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-de-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-de-en', sourceLang: 'de', targetLang: 'en' },
  { id: 'opus-mt-en-de', type: 'translation', name: 'Opus-MT (en → de)', languages: ['en', 'de'], totalSizeMb: 110, cdnPath: 'opus-mt-en-de', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-de', sourceLang: 'en', targetLang: 'de' },
  { id: 'opus-mt-fr-en', type: 'translation', name: 'Opus-MT (fr → en)', languages: ['fr', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-fr-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-fr-en', sourceLang: 'fr', targetLang: 'en' },
  { id: 'opus-mt-en-fr', type: 'translation', name: 'Opus-MT (en → fr)', languages: ['en', 'fr'], totalSizeMb: 110, cdnPath: 'opus-mt-en-fr', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-fr', sourceLang: 'en', targetLang: 'fr' },
  { id: 'opus-mt-es-en', type: 'translation', name: 'Opus-MT (es → en)', languages: ['es', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-es-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-es-en', sourceLang: 'es', targetLang: 'en' },
  { id: 'opus-mt-en-es', type: 'translation', name: 'Opus-MT (en → es)', languages: ['en', 'es'], totalSizeMb: 110, cdnPath: 'opus-mt-en-es', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-es', sourceLang: 'en', targetLang: 'es' },

  // ── English → Other Languages ──────────────────────────────────────────
  { id: 'opus-mt-en-af', type: 'translation', name: 'Opus-MT (en → af)', languages: ['en', 'af'], totalSizeMb: 110, cdnPath: 'opus-mt-en-af', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-af', sourceLang: 'en', targetLang: 'af' },
  { id: 'opus-mt-en-ar', type: 'translation', name: 'Opus-MT (en → ar)', languages: ['en', 'ar'], totalSizeMb: 110, cdnPath: 'opus-mt-en-ar', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-ar', sourceLang: 'en', targetLang: 'ar' },
  { id: 'opus-mt-en-cs', type: 'translation', name: 'Opus-MT (en → cs)', languages: ['en', 'cs'], totalSizeMb: 110, cdnPath: 'opus-mt-en-cs', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-cs', sourceLang: 'en', targetLang: 'cs' },
  { id: 'opus-mt-en-da', type: 'translation', name: 'Opus-MT (en → da)', languages: ['en', 'da'], totalSizeMb: 110, cdnPath: 'opus-mt-en-da', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-da', sourceLang: 'en', targetLang: 'da' },
  { id: 'opus-mt-en-nl', type: 'translation', name: 'Opus-MT (en → nl)', languages: ['en', 'nl'], totalSizeMb: 110, cdnPath: 'opus-mt-en-nl', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-nl', sourceLang: 'en', targetLang: 'nl' },
  { id: 'opus-mt-en-fi', type: 'translation', name: 'Opus-MT (en → fi)', languages: ['en', 'fi'], totalSizeMb: 110, cdnPath: 'opus-mt-en-fi', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-fi', sourceLang: 'en', targetLang: 'fi' },
  { id: 'opus-mt-en-hi', type: 'translation', name: 'Opus-MT (en → hi)', languages: ['en', 'hi'], totalSizeMb: 110, cdnPath: 'opus-mt-en-hi', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-hi', sourceLang: 'en', targetLang: 'hi' },
  { id: 'opus-mt-en-hu', type: 'translation', name: 'Opus-MT (en → hu)', languages: ['en', 'hu'], totalSizeMb: 110, cdnPath: 'opus-mt-en-hu', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-hu', sourceLang: 'en', targetLang: 'hu' },
  { id: 'opus-mt-en-id', type: 'translation', name: 'Opus-MT (en → id)', languages: ['en', 'id'], totalSizeMb: 110, cdnPath: 'opus-mt-en-id', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-id', sourceLang: 'en', targetLang: 'id' },
  { id: 'opus-mt-en-mul', type: 'translation', name: 'Opus-MT (en → mul)', languages: ['en', 'mul'], totalSizeMb: 110, cdnPath: 'opus-mt-en-mul', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-mul', sourceLang: 'en', targetLang: 'mul' },
  { id: 'opus-mt-en-ro', type: 'translation', name: 'Opus-MT (en → ro)', languages: ['en', 'ro'], totalSizeMb: 110, cdnPath: 'opus-mt-en-ro', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-ro', sourceLang: 'en', targetLang: 'ro' },
  { id: 'opus-mt-en-ru', type: 'translation', name: 'Opus-MT (en → ru)', languages: ['en', 'ru'], totalSizeMb: 110, cdnPath: 'opus-mt-en-ru', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-ru', sourceLang: 'en', targetLang: 'ru' },
  { id: 'opus-mt-en-sv', type: 'translation', name: 'Opus-MT (en → sv)', languages: ['en', 'sv'], totalSizeMb: 110, cdnPath: 'opus-mt-en-sv', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-sv', sourceLang: 'en', targetLang: 'sv' },
  { id: 'opus-mt-en-uk', type: 'translation', name: 'Opus-MT (en → uk)', languages: ['en', 'uk'], totalSizeMb: 110, cdnPath: 'opus-mt-en-uk', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-uk', sourceLang: 'en', targetLang: 'uk' },
  { id: 'opus-mt-en-vi', type: 'translation', name: 'Opus-MT (en → vi)', languages: ['en', 'vi'], totalSizeMb: 110, cdnPath: 'opus-mt-en-vi', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-vi', sourceLang: 'en', targetLang: 'vi' },
  { id: 'opus-mt-en-xh', type: 'translation', name: 'Opus-MT (en → xh)', languages: ['en', 'xh'], totalSizeMb: 110, cdnPath: 'opus-mt-en-xh', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-en-xh', sourceLang: 'en', targetLang: 'xh' },

  // ── Other Languages → English ──────────────────────────────────────────
  { id: 'opus-mt-af-en', type: 'translation', name: 'Opus-MT (af → en)', languages: ['af', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-af-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-af-en', sourceLang: 'af', targetLang: 'en' },
  { id: 'opus-mt-ar-en', type: 'translation', name: 'Opus-MT (ar → en)', languages: ['ar', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-ar-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-ar-en', sourceLang: 'ar', targetLang: 'en' },
  { id: 'opus-mt-bat-en', type: 'translation', name: 'Opus-MT (bat → en)', languages: ['bat', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-bat-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-bat-en', sourceLang: 'bat', targetLang: 'en' },
  { id: 'opus-mt-cs-en', type: 'translation', name: 'Opus-MT (cs → en)', languages: ['cs', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-cs-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-cs-en', sourceLang: 'cs', targetLang: 'en' },
  { id: 'opus-mt-hi-en', type: 'translation', name: 'Opus-MT (hi → en)', languages: ['hi', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-hi-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-hi-en', sourceLang: 'hi', targetLang: 'en' },
  { id: 'opus-mt-id-en', type: 'translation', name: 'Opus-MT (id → en)', languages: ['id', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-id-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-id-en', sourceLang: 'id', targetLang: 'en' },
  { id: 'opus-mt-it-en', type: 'translation', name: 'Opus-MT (it → en)', languages: ['it', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-it-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-it-en', sourceLang: 'it', targetLang: 'en' },
  { id: 'opus-mt-nl-en', type: 'translation', name: 'Opus-MT (nl → en)', languages: ['nl', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-nl-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-nl-en', sourceLang: 'nl', targetLang: 'en' },
  { id: 'opus-mt-pl-en', type: 'translation', name: 'Opus-MT (pl → en)', languages: ['pl', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-pl-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-pl-en', sourceLang: 'pl', targetLang: 'en' },
  { id: 'opus-mt-ru-en', type: 'translation', name: 'Opus-MT (ru → en)', languages: ['ru', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-ru-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-ru-en', sourceLang: 'ru', targetLang: 'en' },
  { id: 'opus-mt-sv-en', type: 'translation', name: 'Opus-MT (sv → en)', languages: ['sv', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-sv-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-sv-en', sourceLang: 'sv', targetLang: 'en' },
  { id: 'opus-mt-tr-en', type: 'translation', name: 'Opus-MT (tr → en)', languages: ['tr', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-tr-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-tr-en', sourceLang: 'tr', targetLang: 'en' },
  { id: 'opus-mt-uk-en', type: 'translation', name: 'Opus-MT (uk → en)', languages: ['uk', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-uk-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-uk-en', sourceLang: 'uk', targetLang: 'en' },
  { id: 'opus-mt-xh-en', type: 'translation', name: 'Opus-MT (xh → en)', languages: ['xh', 'en'], totalSizeMb: 110, cdnPath: 'opus-mt-xh-en', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-xh-en', sourceLang: 'xh', targetLang: 'en' },

  // ── Non-English Pairs ──────────────────────────────────────────────────
  { id: 'opus-mt-da-de', type: 'translation', name: 'Opus-MT (da → de)', languages: ['da', 'de'], totalSizeMb: 110, cdnPath: 'opus-mt-da-de', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-da-de', sourceLang: 'da', targetLang: 'de' },
  { id: 'opus-mt-fi-de', type: 'translation', name: 'Opus-MT (fi → de)', languages: ['fi', 'de'], totalSizeMb: 110, cdnPath: 'opus-mt-fi-de', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-fi-de', sourceLang: 'fi', targetLang: 'de' },
  { id: 'opus-mt-fr-de', type: 'translation', name: 'Opus-MT (fr → de)', languages: ['fr', 'de'], totalSizeMb: 110, cdnPath: 'opus-mt-fr-de', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-fr-de', sourceLang: 'fr', targetLang: 'de' },
  { id: 'opus-mt-de-fr', type: 'translation', name: 'Opus-MT (de → fr)', languages: ['de', 'fr'], totalSizeMb: 110, cdnPath: 'opus-mt-de-fr', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-de-fr', sourceLang: 'de', targetLang: 'fr' },
  { id: 'opus-mt-fr-ro', type: 'translation', name: 'Opus-MT (fr → ro)', languages: ['fr', 'ro'], totalSizeMb: 110, cdnPath: 'opus-mt-fr-ro', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-fr-ro', sourceLang: 'fr', targetLang: 'ro' },
  { id: 'opus-mt-ro-fr', type: 'translation', name: 'Opus-MT (ro → fr)', languages: ['ro', 'fr'], totalSizeMb: 110, cdnPath: 'opus-mt-ro-fr', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-ro-fr', sourceLang: 'ro', targetLang: 'fr' },
  { id: 'opus-mt-fr-ru', type: 'translation', name: 'Opus-MT (fr → ru)', languages: ['fr', 'ru'], totalSizeMb: 110, cdnPath: 'opus-mt-fr-ru', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-fr-ru', sourceLang: 'fr', targetLang: 'ru' },
  { id: 'opus-mt-ru-fr', type: 'translation', name: 'Opus-MT (ru → fr)', languages: ['ru', 'fr'], totalSizeMb: 110, cdnPath: 'opus-mt-ru-fr', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-ru-fr', sourceLang: 'ru', targetLang: 'fr' },
  { id: 'opus-mt-fr-es', type: 'translation', name: 'Opus-MT (fr → es)', languages: ['fr', 'es'], totalSizeMb: 110, cdnPath: 'opus-mt-fr-es', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-fr-es', sourceLang: 'fr', targetLang: 'es' },
  { id: 'opus-mt-es-fr', type: 'translation', name: 'Opus-MT (es → fr)', languages: ['es', 'fr'], totalSizeMb: 110, cdnPath: 'opus-mt-es-fr', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-es-fr', sourceLang: 'es', targetLang: 'fr' },
  { id: 'opus-mt-de-es', type: 'translation', name: 'Opus-MT (de → es)', languages: ['de', 'es'], totalSizeMb: 110, cdnPath: 'opus-mt-de-es', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-de-es', sourceLang: 'de', targetLang: 'es' },
  { id: 'opus-mt-es-de', type: 'translation', name: 'Opus-MT (es → de)', languages: ['es', 'de'], totalSizeMb: 110, cdnPath: 'opus-mt-es-de', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-es-de', sourceLang: 'es', targetLang: 'de' },
  { id: 'opus-mt-it-fr', type: 'translation', name: 'Opus-MT (it → fr)', languages: ['it', 'fr'], totalSizeMb: 110, cdnPath: 'opus-mt-it-fr', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-it-fr', sourceLang: 'it', targetLang: 'fr' },
  { id: 'opus-mt-it-es', type: 'translation', name: 'Opus-MT (it → es)', languages: ['it', 'es'], totalSizeMb: 110, cdnPath: 'opus-mt-it-es', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-it-es', sourceLang: 'it', targetLang: 'es' },
  { id: 'opus-mt-es-it', type: 'translation', name: 'Opus-MT (es → it)', languages: ['es', 'it'], totalSizeMb: 110, cdnPath: 'opus-mt-es-it', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-es-it', sourceLang: 'es', targetLang: 'it' },
  { id: 'opus-mt-no-de', type: 'translation', name: 'Opus-MT (no → de)', languages: ['no', 'de'], totalSizeMb: 110, cdnPath: 'opus-mt-no-de', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-no-de', sourceLang: 'no', targetLang: 'de' },
  { id: 'opus-mt-ru-uk', type: 'translation', name: 'Opus-MT (ru → uk)', languages: ['ru', 'uk'], totalSizeMb: 110, cdnPath: 'opus-mt-ru-uk', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-ru-uk', sourceLang: 'ru', targetLang: 'uk' },
  { id: 'opus-mt-uk-ru', type: 'translation', name: 'Opus-MT (uk → ru)', languages: ['uk', 'ru'], totalSizeMb: 110, cdnPath: 'opus-mt-uk-ru', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-uk-ru', sourceLang: 'uk', targetLang: 'ru' },
  { id: 'opus-mt-es-ru', type: 'translation', name: 'Opus-MT (es → ru)', languages: ['es', 'ru'], totalSizeMb: 110, cdnPath: 'opus-mt-es-ru', files: TRANSLATION_FILES, hfModelId: 'Xenova/opus-mt-es-ru', sourceLang: 'es', targetLang: 'ru' },
];

// ─── Language Helpers ────────────────────────────────────────────────────────

import { getLanguageOption } from '../../utils/languages';
import type { LanguageOption } from '../../services/providers/ProviderConfig';

/** Get all unique source languages available across translation models */
export function getTranslationSourceLanguages(): LanguageOption[] {
  const codes = new Set(
    MODEL_MANIFEST.filter(m => m.type === 'translation').map(m => m.sourceLang!)
  );
  return [...codes].map(getLanguageOption).sort((a, b) => a.englishName.localeCompare(b.englishName));
}

/** Get available target languages for a given source language */
export function getTranslationTargetLanguages(sourceLang: string): LanguageOption[] {
  const codes = new Set(
    MODEL_MANIFEST.filter(m => m.type === 'translation' && m.sourceLang === sourceLang).map(m => m.targetLang!)
  );
  return [...codes].map(getLanguageOption).sort((a, b) => a.englishName.localeCompare(b.englishName));
}

// ─── Query Helpers ───────────────────────────────────────────────────────────

/** Get a manifest entry by model ID */
export function getManifestEntry(modelId: string): ModelManifestEntry | undefined {
  return MODEL_MANIFEST.find(m => m.id === modelId);
}

/** Get all manifest entries of a given type */
export function getManifestByType(type: ModelType): ModelManifestEntry[] {
  return MODEL_MANIFEST.filter(m => m.type === type);
}

/** Get ASR models (offline + streaming) that support a given language */
export function getAsrModelsForLanguage(lang: string): ModelManifestEntry[] {
  return MODEL_MANIFEST.filter(
    m => (m.type === 'asr' || m.type === 'asr-stream') && m.languages.includes(lang)
  );
}

/** Get translation model for a language pair */
export function getTranslationModel(sourceLang: string, targetLang: string): ModelManifestEntry | undefined {
  return MODEL_MANIFEST.find(
    m => m.type === 'translation' && m.sourceLang === sourceLang && m.targetLang === targetLang
  );
}

/** Get TTS models that support a given language */
export function getTtsModelsForLanguage(lang: string): ModelManifestEntry[] {
  return MODEL_MANIFEST.filter(m => m.type === 'tts' && m.languages.includes(lang));
}
