// Generated by scripts/gen-viewer-strings.mjs from src/locales/*/translation.json.
// Do not edit: change the catalogs, then run `node scripts/gen-viewer-strings.mjs`.
export const VIEWER_WORDS: Record<string, unknown> = {
  "ar": {
    "title": "ترجمة Sokuji",
    "connecting": "جاري الاتصال…",
    "original": "الأصل",
    "enter": {
      "iRead": "أريد أن أقرأ",
      "both": "اللغتان معًا",
      "bothHint": "{{first}} في الأعلى، و{{second}} في الأسفل",
      "start": "ابدأ القراءة",
      "insecureNote": "قد يصف متصفحك هذه الصفحة بأنها غير آمنة. هذا عنوان على الشبكة المحلية: الترجمة تصل مباشرةً من حاسوب المتحدث."
    },
    "status": {
      "waiting": "في انتظار البدء",
      "live": "مباشر",
      "paused": "متوقف مؤقتًا",
      "reconnecting": "جاري إعادة الاتصال…",
      "ended": "انتهت المشاركة"
    },
    "notice": {
      "cleared": "مسح المتحدث الترجمة السابقة",
      "restarted": "بدأ المتحدث جولة جديدة"
    },
    "legend": {
      "onSite": "حضوري",
      "remote": "عن بُعد"
    },
    "backToLive": "العودة إلى المباشر",
    "dock": {
      "textSize": "حجم النص",
      "more": "المزيد"
    },
    "settings": {
      "title": "إعدادات العرض",
      "iRead": "لغة القراءة",
      "textSize": "حجم النص",
      "sizes": {
        "small": "صغير",
        "medium": "متوسط",
        "large": "كبير",
        "xlarge": "كبير جدًا"
      },
      "theme": "الألوان",
      "themes": {
        "dark": "داكن",
        "light": "فاتح",
        "contrast": "تباين عالٍ"
      },
      "completeOnly": "الجمل المكتملة فقط",
      "completeOnlyHint": "إخفاء الكلام الذي لم يكتمل بعد",
      "keepAwake": "إبقاء الشاشة مضاءة",
      "save": "حفظ هذه الترجمة",
      "saveHint": "ملف .txt يضم ما في هذه الصفحة",
      "saveButton": "حفظ",
      "close": "إغلاق",
      "aiNote": "تُنشأ الترجمة بالذكاء الاصطناعي وقد تحتوي على أخطاء."
    },
    "shortcuts": "+ − حجم النص · B اللغتان · F ملء الشاشة · End العودة إلى المباشر",
    "transcript": {
      "header": "ترجمة Sokuji، حُفظت في {{time}}"
    },
    "present": {
      "title": "اقرأ الترجمة على هاتفك أو حاسوبك",
      "step1": "اتصل بشبكة Wi‑Fi",
      "password": "كلمة المرور: {{password}}",
      "step2": "امسح الرمز بهاتفك، أو اكتب هذا العنوان على الحاسوب",
      "step3": "اختر اللغة التي تريد قراءتها",
      "noInstall": "بلا تطبيق ولا تسجيل دخول",
      "sameNetwork": "لا يُفتح هذا العنوان إلا من الشبكة نفسها",
      "androidChrome": "لا يفتحها Chrome على Android؟ اسمح بذلك من الإعدادات ← التطبيقات ← Chrome ← الأذونات ← الأجهزة المجاورة.",
      "watching": "المشاهدون: {{count}}",
      "fullscreen": "ملء الشاشة",
      "windowTitle": "صفحة عرض Sokuji",
      "ended": "انتهت المشاركة"
    }
  },
  "bn": {
    "title": "Sokuji সাবটাইটেল",
    "connecting": "সংযোগ হচ্ছে…",
    "original": "মূল",
    "enter": {
      "iRead": "আমি পড়তে চাই",
      "both": "দুই ভাষাই",
      "bothHint": "উপরে {{first}}, নিচে {{second}}",
      "start": "পড়া শুরু করুন",
      "insecureNote": "আপনার ব্রাউজার এই পেজকে অনিরাপদ বলতে পারে। এটি একটি স্থানীয় নেটওয়ার্কের ঠিকানা: সাবটাইটেল সরাসরি বক্তার কম্পিউটার থেকে আসে।"
    },
    "status": {
      "waiting": "শুরুর অপেক্ষায়",
      "live": "লাইভ",
      "paused": "বিরতিতে",
      "reconnecting": "আবার সংযোগ হচ্ছে…",
      "ended": "শেয়ারিং শেষ হয়েছে"
    },
    "notice": {
      "cleared": "বক্তা আগের সাবটাইটেল মুছে ফেলেছেন",
      "restarted": "বক্তা নতুন একটি পর্ব শুরু করেছেন"
    },
    "legend": {
      "onSite": "উপস্থিত",
      "remote": "অনলাইন"
    },
    "backToLive": "লাইভে ফিরুন",
    "dock": {
      "textSize": "লেখার আকার",
      "more": "আরও"
    },
    "settings": {
      "title": "প্রদর্শন সেটিংস",
      "iRead": "পড়ার ভাষা",
      "textSize": "লেখার আকার",
      "sizes": {
        "small": "ছোট",
        "medium": "মাঝারি",
        "large": "বড়",
        "xlarge": "খুব বড়"
      },
      "theme": "রং",
      "themes": {
        "dark": "গাঢ়",
        "light": "হালকা",
        "contrast": "উচ্চ কনট্রাস্ট"
      },
      "completeOnly": "শুধু সম্পূর্ণ বাক্য",
      "completeOnlyHint": "যা এখনও বলা হচ্ছে তা লুকান",
      "keepAwake": "স্ক্রিন চালু রাখুন",
      "save": "এই সাবটাইটেল সংরক্ষণ করুন",
      "saveHint": "এই পেজে যা আছে তার একটি .txt ফাইল",
      "saveButton": "সংরক্ষণ",
      "close": "বন্ধ",
      "aiNote": "সাবটাইটেল AI দিয়ে তৈরি, এতে ভুল থাকতে পারে।"
    },
    "shortcuts": "+ − লেখার আকার · B দুই ভাষাই · F পূর্ণস্ক্রিন · End লাইভে ফিরুন",
    "transcript": {
      "header": "Sokuji সাবটাইটেল, সংরক্ষণের সময় {{time}}"
    },
    "present": {
      "title": "আপনার ফোন বা কম্পিউটারে সাবটাইটেল পড়ুন",
      "step1": "Wi‑Fi-তে যুক্ত হোন",
      "password": "পাসওয়ার্ড: {{password}}",
      "step2": "ফোন দিয়ে স্ক্যান করুন, অথবা কম্পিউটারে এই ঠিকানাটি লিখুন",
      "step3": "যে ভাষায় পড়তে চান তা বেছে নিন",
      "noInstall": "অ্যাপ বা সাইন ইন কিছুই লাগবে না",
      "sameNetwork": "এই ঠিকানা শুধু একই নেটওয়ার্ক থেকে খোলে",
      "androidChrome": "Android-এ Chrome খুলছে না? সেটিংস → অ্যাপ → Chrome → অনুমতি → আশেপাশের ডিভাইস থেকে অনুমতি দিন।",
      "watching": "দেখছেন: {{count}}",
      "fullscreen": "পূর্ণস্ক্রিন",
      "windowTitle": "Sokuji প্রজেক্টর পেজ",
      "ended": "শেয়ারিং শেষ হয়েছে"
    }
  },
  "de": {
    "title": "Sokuji-Untertitel",
    "connecting": "Verbinden…",
    "original": "Original",
    "enter": {
      "iRead": "Ich möchte lesen",
      "both": "Beide Sprachen",
      "bothHint": "{{first}} oben, {{second}} darunter",
      "start": "Lesen starten",
      "insecureNote": "Ihr Browser bezeichnet diese Seite möglicherweise als nicht sicher. Es ist eine Adresse im lokalen Netzwerk: Die Untertitel kommen direkt vom Computer des Sprechers."
    },
    "status": {
      "waiting": "Wartet auf den Start",
      "live": "Live",
      "paused": "Pausiert",
      "reconnecting": "Verbindung wird wiederhergestellt…",
      "ended": "Das Teilen wurde beendet"
    },
    "notice": {
      "cleared": "Der Sprecher hat die bisherigen Untertitel gelöscht",
      "restarted": "Der Sprecher hat eine neue Runde gestartet"
    },
    "legend": {
      "onSite": "Vor Ort",
      "remote": "Online"
    },
    "backToLive": "Zurück zu Live",
    "dock": {
      "textSize": "Schriftgröße",
      "more": "Mehr"
    },
    "settings": {
      "title": "Anzeige",
      "iRead": "Ich lese",
      "textSize": "Schriftgröße",
      "sizes": {
        "small": "Klein",
        "medium": "Mittel",
        "large": "Groß",
        "xlarge": "Sehr groß"
      },
      "theme": "Farben",
      "themes": {
        "dark": "Dunkel",
        "light": "Hell",
        "contrast": "Hoher Kontrast"
      },
      "completeOnly": "Nur vollständige Sätze",
      "completeOnlyHint": "Blendet aus, was gerade noch gesprochen wird",
      "keepAwake": "Bildschirm eingeschaltet lassen",
      "save": "Diese Untertitel speichern",
      "saveHint": "Eine .txt-Datei mit dem Inhalt dieser Seite",
      "saveButton": "Speichern",
      "close": "Schließen",
      "aiNote": "Die Untertitel werden von KI erzeugt und können Fehler enthalten."
    },
    "shortcuts": "+ − Schriftgröße · B beide Sprachen · F Vollbild · End zurück zu Live",
    "transcript": {
      "header": "Sokuji-Untertitel, gespeichert am {{time}}"
    },
    "present": {
      "title": "Untertitel auf dem Smartphone oder Computer lesen",
      "step1": "Mit dem Wi‑Fi verbinden",
      "password": "Passwort: {{password}}",
      "step2": "Mit dem Smartphone scannen oder diese Adresse am Computer eingeben",
      "step3": "Die gewünschte Sprache wählen",
      "noInstall": "Keine App, keine Anmeldung",
      "sameNetwork": "Diese Adresse funktioniert nur im selben Netzwerk",
      "androidChrome": "Öffnet Chrome auf Android die Seite nicht? Unter Einstellungen → Apps → Chrome → Berechtigungen → Geräte in der Nähe erlauben.",
      "watching": "Zuschauer: {{count}}",
      "fullscreen": "Vollbild",
      "windowTitle": "Sokuji-Projektionsseite",
      "ended": "Das Teilen wurde beendet"
    }
  },
  "en": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "androidChrome": "Android Chrome won't open it? Allow it in Settings → Apps → Chrome → Permissions → Nearby devices.",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "es": {
    "title": "Subtítulos de Sokuji",
    "connecting": "Conectando…",
    "original": "Original",
    "enter": {
      "iRead": "Quiero leer",
      "both": "Ambos idiomas",
      "bothHint": "{{first}} arriba, {{second}} debajo",
      "start": "Empezar a leer",
      "insecureNote": "Puede que tu navegador diga que esta página no es segura. Es una dirección de la red local: los subtítulos llegan directamente del ordenador de quien habla."
    },
    "status": {
      "waiting": "Esperando el inicio",
      "live": "En directo",
      "paused": "En pausa",
      "reconnecting": "Reconectando…",
      "ended": "Se ha dejado de compartir"
    },
    "notice": {
      "cleared": "Quien habla ha borrado los subtítulos anteriores",
      "restarted": "Quien habla ha empezado una nueva ronda"
    },
    "legend": {
      "onSite": "Presencial",
      "remote": "En línea"
    },
    "backToLive": "Volver al directo",
    "dock": {
      "textSize": "Tamaño de fuente",
      "more": "Más"
    },
    "settings": {
      "title": "Visualización",
      "iRead": "Yo leo",
      "textSize": "Tamaño de fuente",
      "sizes": {
        "small": "Pequeño",
        "medium": "Mediano",
        "large": "Grande",
        "xlarge": "Muy grande"
      },
      "theme": "Colores",
      "themes": {
        "dark": "Oscuro",
        "light": "Claro",
        "contrast": "Alto contraste"
      },
      "completeOnly": "Solo frases completas",
      "completeOnlyHint": "Oculta lo que aún se está diciendo",
      "keepAwake": "Mantener la pantalla encendida",
      "save": "Guardar estos subtítulos",
      "saveHint": "Un archivo .txt con lo que hay en esta página",
      "saveButton": "Guardar",
      "close": "Cerrar",
      "aiNote": "Los subtítulos los genera una IA y pueden contener errores."
    },
    "shortcuts": "+ − tamaño de fuente · B ambos idiomas · F pantalla completa · End volver al directo",
    "transcript": {
      "header": "Subtítulos de Sokuji, guardados el {{time}}"
    },
    "present": {
      "title": "Lee los subtítulos en tu móvil u ordenador",
      "step1": "Conéctate al Wi‑Fi",
      "password": "Contraseña: {{password}}",
      "step2": "Escanea con el móvil o escribe esta dirección en un ordenador",
      "step3": "Elige el idioma que quieres leer",
      "noInstall": "Sin app ni inicio de sesión",
      "sameNetwork": "Esta dirección solo funciona en la misma red",
      "androidChrome": "¿Chrome en Android no la abre? Permítelo en Ajustes → Aplicaciones → Chrome → Permisos → Dispositivos cercanos.",
      "watching": "Espectadores: {{count}}",
      "fullscreen": "Pantalla completa",
      "windowTitle": "Página de proyección de Sokuji",
      "ended": "Se ha dejado de compartir"
    }
  },
  "fa": {
    "title": "زیرنویس Sokuji",
    "connecting": "در حال اتصال…",
    "original": "اصلی",
    "enter": {
      "iRead": "می‌خواهم بخوانم",
      "both": "هر دو زبان",
      "bothHint": "{{first}} بالا، {{second}} پایین",
      "start": "شروع خواندن",
      "insecureNote": "ممکن است مرورگر شما این صفحه را «ناامن» بنامد. این یک آدرس شبکهٔ محلی است: زیرنویس مستقیم از رایانهٔ سخنران می‌آید."
    },
    "status": {
      "waiting": "در انتظار شروع",
      "live": "زنده",
      "paused": "متوقف شده",
      "reconnecting": "در حال اتصال دوباره…",
      "ended": "اشتراک‌گذاری پایان یافت"
    },
    "notice": {
      "cleared": "سخنران زیرنویس‌های قبلی را پاک کرد",
      "restarted": "سخنران دور تازه‌ای را شروع کرد"
    },
    "legend": {
      "onSite": "حضوری",
      "remote": "از راه دور"
    },
    "backToLive": "بازگشت به پخش زنده",
    "dock": {
      "textSize": "اندازهٔ متن",
      "more": "بیشتر"
    },
    "settings": {
      "title": "تنظیمات نمایش",
      "iRead": "زبان خواندن",
      "textSize": "اندازهٔ متن",
      "sizes": {
        "small": "کوچک",
        "medium": "متوسط",
        "large": "بزرگ",
        "xlarge": "خیلی بزرگ"
      },
      "theme": "رنگ‌ها",
      "themes": {
        "dark": "تیره",
        "light": "روشن",
        "contrast": "کنتراست بالا"
      },
      "completeOnly": "فقط جمله‌های کامل",
      "completeOnlyHint": "جمله‌هایی که هنوز تمام نشده‌اند نمایش داده نشوند",
      "keepAwake": "روشن نگه داشتن صفحه",
      "save": "ذخیرهٔ این زیرنویس",
      "saveHint": "یک فایل .txt از آنچه در این صفحه است",
      "saveButton": "ذخیره",
      "close": "بستن",
      "aiNote": "زیرنویس با هوش مصنوعی ساخته می‌شود و ممکن است اشتباه داشته باشد."
    },
    "shortcuts": "+ − اندازهٔ متن · B هر دو زبان · F تمام‌صفحه · End بازگشت به پخش زنده",
    "transcript": {
      "header": "زیرنویس Sokuji، ذخیره‌شده در {{time}}"
    },
    "present": {
      "title": "زیرنویس را روی گوشی یا رایانهٔ خود بخوانید",
      "step1": "به Wi‑Fi وصل شوید",
      "password": "رمز عبور: {{password}}",
      "step2": "با گوشی اسکن کنید، یا این آدرس را در رایانه وارد کنید",
      "step3": "زبانی را که می‌خواهید بخوانید انتخاب کنید",
      "noInstall": "بدون نصب برنامه، بدون ورود به حساب",
      "sameNetwork": "این آدرس فقط در همین شبکه باز می‌شود",
      "androidChrome": "Chrome در Android آن را باز نمی‌کند؟ در تنظیمات ← برنامه‌ها ← Chrome ← اجازه‌ها ← دستگاه‌های اطراف اجازه دهید.",
      "watching": "بینندگان: {{count}}",
      "fullscreen": "تمام‌صفحه",
      "windowTitle": "صفحهٔ پروژکتور Sokuji",
      "ended": "اشتراک‌گذاری پایان یافت"
    }
  },
  "fi": {
    "title": "Sokuji-tekstitys",
    "connecting": "Yhdistetään…",
    "original": "Alkuperäinen",
    "enter": {
      "iRead": "Haluan lukea",
      "both": "Molemmat kielet",
      "bothHint": "{{first}} ylhäällä, {{second}} alla",
      "start": "Aloita lukeminen",
      "insecureNote": "Selain saattaa sanoa, ettei tämä sivu ole suojattu. Kyse on lähiverkon osoitteesta: tekstitys tulee suoraan puhujan tietokoneelta."
    },
    "status": {
      "waiting": "Odotetaan alkua",
      "live": "Suorana",
      "paused": "Tauolla",
      "reconnecting": "Yhdistetään uudelleen…",
      "ended": "Jakaminen on päättynyt"
    },
    "notice": {
      "cleared": "Puhuja tyhjensi aiemmat tekstitykset",
      "restarted": "Puhuja aloitti uuden kierroksen"
    },
    "legend": {
      "onSite": "Paikan päällä",
      "remote": "Etänä"
    },
    "backToLive": "Takaisin uusimpaan",
    "dock": {
      "textSize": "Fonttikoko",
      "more": "Lisää"
    },
    "settings": {
      "title": "Näyttö",
      "iRead": "Luen",
      "textSize": "Fonttikoko",
      "sizes": {
        "small": "Pieni",
        "medium": "Keskikokoinen",
        "large": "Suuri",
        "xlarge": "Erittäin suuri"
      },
      "theme": "Värit",
      "themes": {
        "dark": "Tumma",
        "light": "Vaalea",
        "contrast": "Suuri kontrasti"
      },
      "completeOnly": "Vain valmiit lauseet",
      "completeOnlyHint": "Piilota se, mitä vielä sanotaan",
      "keepAwake": "Pidä näyttö päällä",
      "save": "Tallenna tämä tekstitys",
      "saveHint": ".txt-tiedosto tämän sivun sisällöstä",
      "saveButton": "Tallenna",
      "close": "Sulje",
      "aiNote": "Tekstityksen tuottaa tekoäly, ja siinä voi olla virheitä."
    },
    "shortcuts": "+ − fonttikoko · B molemmat kielet · F koko näyttö · End takaisin uusimpaan",
    "transcript": {
      "header": "Sokuji-tekstitys, tallennettu {{time}}"
    },
    "present": {
      "title": "Lue tekstitys puhelimella tai tietokoneella",
      "step1": "Yhdistä Wi‑Fi-verkkoon",
      "password": "Salasana: {{password}}",
      "step2": "Skannaa puhelimella tai kirjoita tämä osoite tietokoneella",
      "step3": "Valitse kieli, jota haluat lukea",
      "noInstall": "Ei sovellusta, ei kirjautumista",
      "sameNetwork": "Tämä osoite aukeaa vain samassa verkossa",
      "androidChrome": "Eikö Chrome avaa sivua Androidissa? Salli se kohdassa Asetukset → Sovellukset → Chrome → Käyttöoikeudet → Lähellä olevat laitteet.",
      "watching": "Katsojia: {{count}}",
      "fullscreen": "Koko näyttö",
      "windowTitle": "Sokuji-projektorisivu",
      "ended": "Jakaminen on päättynyt"
    }
  },
  "fil": {
    "title": "Mga subtitle ng Sokuji",
    "connecting": "Kumokonekta…",
    "original": "Orihinal",
    "enter": {
      "iRead": "Gusto kong basahin",
      "both": "Parehong wika",
      "bothHint": "{{first}} sa itaas, {{second}} sa ibaba",
      "start": "Simulang magbasa",
      "insecureNote": "Maaaring sabihin ng browser mo na hindi secure ang page na ito. Address ito sa local network: direktang galing ang mga subtitle sa computer ng nagsasalita."
    },
    "status": {
      "waiting": "Hinihintay magsimula",
      "live": "Live",
      "paused": "Naka-pause",
      "reconnecting": "Muling kumokonekta…",
      "ended": "Tapos na ang pagbabahagi"
    },
    "notice": {
      "cleared": "Binura ng nagsasalita ang mga naunang subtitle",
      "restarted": "Nagsimula ulit ang nagsasalita"
    },
    "legend": {
      "onSite": "Onsite",
      "remote": "Online"
    },
    "backToLive": "Bumalik sa live",
    "dock": {
      "textSize": "Laki ng teksto",
      "more": "Higit pa"
    },
    "settings": {
      "title": "Display",
      "iRead": "Gusto kong basahin",
      "textSize": "Laki ng teksto",
      "sizes": {
        "small": "Maliit",
        "medium": "Katamtaman",
        "large": "Malaki",
        "xlarge": "Napakalaki"
      },
      "theme": "Mga kulay",
      "themes": {
        "dark": "Madilim",
        "light": "Maliwanag",
        "contrast": "Mataas na contrast"
      },
      "completeOnly": "Buong pangungusap lang",
      "completeOnlyHint": "Itago ang sinasabi pa lang",
      "keepAwake": "Panatilihing bukas ang screen",
      "save": "I-save ang mga subtitle na ito",
      "saveHint": "Isang .txt file ng nasa page na ito",
      "saveButton": "I-save",
      "close": "Isara",
      "aiNote": "Gawa ng AI ang mga subtitle at maaaring may mali."
    },
    "shortcuts": "+ − laki ng teksto · B parehong wika · F fullscreen · End bumalik sa live",
    "transcript": {
      "header": "Mga subtitle ng Sokuji, na-save noong {{time}}"
    },
    "present": {
      "title": "Basahin ang mga subtitle sa phone o computer mo",
      "step1": "Kumonekta sa Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "I-scan gamit ang phone, o i-type ang address na ito sa computer",
      "step3": "Piliin ang wikang gusto mong basahin",
      "noInstall": "Walang app, walang sign-in",
      "sameNetwork": "Bubukas lang ang address na ito sa parehong network",
      "androidChrome": "Hindi mabuksan sa Chrome sa Android? Payagan ito sa Settings → Apps → Chrome → Permissions → Nearby devices.",
      "watching": "Nanonood: {{count}}",
      "fullscreen": "Fullscreen",
      "windowTitle": "Projector page ng Sokuji",
      "ended": "Tapos na ang pagbabahagi"
    }
  },
  "fr": {
    "title": "Sous-titres Sokuji",
    "connecting": "Connexion…",
    "original": "Original",
    "enter": {
      "iRead": "Je veux lire",
      "both": "Les deux langues",
      "bothHint": "{{first}} en haut, {{second}} en dessous",
      "start": "Commencer la lecture",
      "insecureNote": "Votre navigateur peut indiquer que cette page n'est pas sécurisée. C'est une adresse du réseau local : les sous-titres viennent directement de l'ordinateur de l'intervenant."
    },
    "status": {
      "waiting": "En attente du début",
      "live": "En direct",
      "paused": "En pause",
      "reconnecting": "Reconnexion…",
      "ended": "Le partage est terminé"
    },
    "notice": {
      "cleared": "L'intervenant a effacé les sous-titres précédents",
      "restarted": "L'intervenant a lancé une nouvelle série"
    },
    "legend": {
      "onSite": "Sur place",
      "remote": "À distance"
    },
    "backToLive": "Revenir au direct",
    "dock": {
      "textSize": "Taille du texte",
      "more": "Plus"
    },
    "settings": {
      "title": "Affichage",
      "iRead": "Je lis",
      "textSize": "Taille du texte",
      "sizes": {
        "small": "Petite",
        "medium": "Moyenne",
        "large": "Grande",
        "xlarge": "Très grande"
      },
      "theme": "Couleurs",
      "themes": {
        "dark": "Sombre",
        "light": "Clair",
        "contrast": "Contraste élevé"
      },
      "completeOnly": "Phrases complètes uniquement",
      "completeOnlyHint": "Masquer ce qui est encore en train d'être dit",
      "keepAwake": "Garder l'écran allumé",
      "save": "Enregistrer ces sous-titres",
      "saveHint": "Un fichier .txt avec le contenu de cette page",
      "saveButton": "Enregistrer",
      "close": "Fermer",
      "aiNote": "Les sous-titres sont générés par IA et peuvent contenir des erreurs."
    },
    "shortcuts": "+ − taille du texte · B les deux langues · F plein écran · End retour au direct",
    "transcript": {
      "header": "Sous-titres Sokuji, enregistrés le {{time}}"
    },
    "present": {
      "title": "Lisez les sous-titres sur votre téléphone ou votre ordinateur",
      "step1": "Connectez-vous au Wi‑Fi",
      "password": "Mot de passe : {{password}}",
      "step2": "Scannez avec votre téléphone, ou saisissez cette adresse sur un ordinateur",
      "step3": "Choisissez la langue que vous voulez lire",
      "noInstall": "Sans application ni compte",
      "sameNetwork": "Cette adresse ne s'ouvre que sur le même réseau",
      "androidChrome": "Chrome sur Android ne l'ouvre pas ? Autorisez-le dans Paramètres → Applications → Chrome → Autorisations → Appareils à proximité.",
      "watching": "Spectateurs : {{count}}",
      "fullscreen": "Plein écran",
      "windowTitle": "Page de projection Sokuji",
      "ended": "Le partage est terminé"
    }
  },
  "he": {
    "title": "כתוביות Sokuji",
    "connecting": "מתחבר…",
    "original": "מקור",
    "enter": {
      "iRead": "אני רוצה לקרוא",
      "both": "שתי השפות",
      "bothHint": "{{first}} למעלה, {{second}} מתחת",
      "start": "התחל לקרוא",
      "insecureNote": "ייתכן שהדפדפן יציין שהדף אינו מאובטח. זו כתובת ברשת המקומית: הכתוביות מגיעות ישירות מהמחשב של הדובר."
    },
    "status": {
      "waiting": "ממתין להתחלה",
      "live": "בשידור חי",
      "paused": "מושהה",
      "reconnecting": "מתחבר מחדש…",
      "ended": "השיתוף הסתיים"
    },
    "notice": {
      "cleared": "הדובר ניקה את הכתוביות הקודמות",
      "restarted": "הדובר התחיל סבב חדש"
    },
    "legend": {
      "onSite": "במקום",
      "remote": "מרחוק"
    },
    "backToLive": "חזרה לשידור החי",
    "dock": {
      "textSize": "גודל טקסט",
      "more": "עוד"
    },
    "settings": {
      "title": "הגדרות תצוגה",
      "iRead": "שפת הקריאה",
      "textSize": "גודל טקסט",
      "sizes": {
        "small": "קטן",
        "medium": "בינוני",
        "large": "גדול",
        "xlarge": "גדול מאוד"
      },
      "theme": "צבעים",
      "themes": {
        "dark": "כהה",
        "light": "בהיר",
        "contrast": "ניגודיות גבוהה"
      },
      "completeOnly": "רק משפטים שלמים",
      "completeOnlyHint": "הסתרת משפטים שעוד לא הסתיימו",
      "keepAwake": "השארת המסך דלוק",
      "save": "שמירת הכתוביות",
      "saveHint": "קובץ .txt עם מה שמופיע בדף הזה",
      "saveButton": "שמירה",
      "close": "סגירה",
      "aiNote": "הכתוביות נוצרות על ידי בינה מלאכותית ועלולות להכיל טעויות."
    },
    "shortcuts": "+ − גודל טקסט · B שתי השפות · F מסך מלא · End חזרה לשידור החי",
    "transcript": {
      "header": "כתוביות Sokuji, נשמרו ב-{{time}}"
    },
    "present": {
      "title": "קראו את הכתוביות בטלפון או במחשב",
      "step1": "התחברו ל-Wi‑Fi",
      "password": "סיסמה: {{password}}",
      "step2": "סרקו בטלפון, או הקלידו את הכתובת הזו במחשב",
      "step3": "בחרו את השפה שאתם רוצים לקרוא",
      "noInstall": "בלי אפליקציה ובלי התחברות",
      "sameNetwork": "הכתובת נפתחת רק מאותה רשת",
      "androidChrome": "Chrome ב-Android לא פותח את הדף? אפשרו זאת בהגדרות ← אפליקציות ← Chrome ← הרשאות ← מכשירים בקרבת מקום.",
      "watching": "צופים: {{count}}",
      "fullscreen": "מסך מלא",
      "windowTitle": "דף ההקרנה של Sokuji",
      "ended": "השיתוף הסתיים"
    }
  },
  "hi": {
    "title": "Sokuji सबटाइटल",
    "connecting": "जुड़ रहे हैं…",
    "original": "मूल",
    "enter": {
      "iRead": "मुझे पढ़ना है",
      "both": "दोनों भाषाएँ",
      "bothHint": "ऊपर {{first}}, नीचे {{second}}",
      "start": "पढ़ना शुरू करें",
      "insecureNote": "आपका ब्राउज़र इस पेज को असुरक्षित बता सकता है। यह स्थानीय नेटवर्क का पता है: सबटाइटल सीधे वक्ता के कंप्यूटर से आते हैं।"
    },
    "status": {
      "waiting": "शुरू होने की प्रतीक्षा",
      "live": "लाइव",
      "paused": "रुका हुआ",
      "reconnecting": "फिर से जुड़ रहे हैं…",
      "ended": "शेयरिंग समाप्त हो गई"
    },
    "notice": {
      "cleared": "वक्ता ने पिछले सबटाइटल साफ़ कर दिए",
      "restarted": "वक्ता ने नया दौर शुरू किया"
    },
    "legend": {
      "onSite": "उपस्थित",
      "remote": "ऑनलाइन"
    },
    "backToLive": "लाइव पर लौटें",
    "dock": {
      "textSize": "टेक्स्ट आकार",
      "more": "और"
    },
    "settings": {
      "title": "प्रदर्शन सेटिंग्स",
      "iRead": "पढ़ने की भाषा",
      "textSize": "टेक्स्ट आकार",
      "sizes": {
        "small": "छोटा",
        "medium": "मध्यम",
        "large": "बड़ा",
        "xlarge": "बहुत बड़ा"
      },
      "theme": "रंग",
      "themes": {
        "dark": "डार्क",
        "light": "लाइट",
        "contrast": "हाई कंट्रास्ट"
      },
      "completeOnly": "केवल पूरे वाक्य",
      "completeOnlyHint": "जो अभी बोला जा रहा है, उसे छिपाएँ",
      "keepAwake": "स्क्रीन चालू रखें",
      "save": "ये सबटाइटल सहेजें",
      "saveHint": "इस पेज पर जो है, उसकी .txt फ़ाइल",
      "saveButton": "सहेजें",
      "close": "बंद करें",
      "aiNote": "सबटाइटल AI से बनाए जाते हैं और इनमें गलतियाँ हो सकती हैं।"
    },
    "shortcuts": "+ − टेक्स्ट आकार · B दोनों भाषाएँ · F फ़ुलस्क्रीन · End लाइव पर लौटें",
    "transcript": {
      "header": "Sokuji सबटाइटल, {{time}} पर सहेजे गए"
    },
    "present": {
      "title": "अपने फ़ोन या कंप्यूटर पर सबटाइटल पढ़ें",
      "step1": "Wi‑Fi से जुड़ें",
      "password": "पासवर्ड: {{password}}",
      "step2": "फ़ोन से स्कैन करें, या कंप्यूटर पर यह पता टाइप करें",
      "step3": "जो भाषा पढ़नी है, उसे चुनें",
      "noInstall": "न ऐप चाहिए, न साइन इन",
      "sameNetwork": "यह पता केवल इसी नेटवर्क पर खुलता है",
      "androidChrome": "Android पर Chrome में नहीं खुल रहा? सेटिंग → ऐप्लिकेशन → Chrome → अनुमतियां → आस-पास के डिवाइस में अनुमति दें।",
      "watching": "देख रहे हैं: {{count}}",
      "fullscreen": "फ़ुलस्क्रीन",
      "windowTitle": "Sokuji प्रोजेक्टर पेज",
      "ended": "शेयरिंग समाप्त हो गई"
    }
  },
  "id": {
    "title": "Subtitle Sokuji",
    "connecting": "Menghubungkan…",
    "original": "Asli",
    "enter": {
      "iRead": "Saya ingin membaca",
      "both": "Kedua bahasa",
      "bothHint": "{{first}} di atas, {{second}} di bawah",
      "start": "Mulai membaca",
      "insecureNote": "Browser Anda mungkin menyebut halaman ini tidak aman. Ini alamat jaringan lokal: subtitle dikirim langsung dari komputer pembicara."
    },
    "status": {
      "waiting": "Menunggu dimulai",
      "live": "Langsung",
      "paused": "Dijeda",
      "reconnecting": "Menghubungkan ulang…",
      "ended": "Berbagi telah berakhir"
    },
    "notice": {
      "cleared": "Pembicara menghapus subtitle sebelumnya",
      "restarted": "Pembicara memulai sesi baru"
    },
    "legend": {
      "onSite": "Di lokasi",
      "remote": "Online"
    },
    "backToLive": "Ke terbaru",
    "dock": {
      "textSize": "Ukuran teks",
      "more": "Lainnya"
    },
    "settings": {
      "title": "Tampilan",
      "iRead": "Saya membaca",
      "textSize": "Ukuran teks",
      "sizes": {
        "small": "Kecil",
        "medium": "Sedang",
        "large": "Besar",
        "xlarge": "Sangat besar"
      },
      "theme": "Warna",
      "themes": {
        "dark": "Gelap",
        "light": "Terang",
        "contrast": "Kontras tinggi"
      },
      "completeOnly": "Hanya kalimat lengkap",
      "completeOnlyHint": "Sembunyikan yang masih diucapkan",
      "keepAwake": "Biarkan layar tetap menyala",
      "save": "Simpan subtitle ini",
      "saveHint": "File .txt berisi apa yang ada di halaman ini",
      "saveButton": "Simpan",
      "close": "Tutup",
      "aiNote": "Subtitle dibuat oleh AI dan mungkin mengandung kesalahan."
    },
    "shortcuts": "+ − ukuran teks · B kedua bahasa · F layar penuh · End ke terbaru",
    "transcript": {
      "header": "Subtitle Sokuji, disimpan {{time}}"
    },
    "present": {
      "title": "Baca subtitle di ponsel atau komputer Anda",
      "step1": "Sambungkan ke Wi‑Fi",
      "password": "Kata sandi: {{password}}",
      "step2": "Pindai dengan ponsel, atau ketik alamat ini di komputer",
      "step3": "Pilih bahasa yang ingin dibaca",
      "noInstall": "Tanpa aplikasi, tanpa masuk",
      "sameNetwork": "Alamat ini hanya bisa dibuka di jaringan yang sama",
      "androidChrome": "Chrome di Android tidak bisa membukanya? Izinkan di Setelan → Aplikasi → Chrome → Izin → Perangkat di sekitar.",
      "watching": "Menonton: {{count}}",
      "fullscreen": "Layar penuh",
      "windowTitle": "Halaman proyektor Sokuji",
      "ended": "Berbagi telah berakhir"
    }
  },
  "it": {
    "title": "Sottotitoli Sokuji",
    "connecting": "Connessione…",
    "original": "Originale",
    "enter": {
      "iRead": "Voglio leggere",
      "both": "Entrambe le lingue",
      "bothHint": "{{first}} sopra, {{second}} sotto",
      "start": "Inizia a leggere",
      "insecureNote": "Il browser potrebbe segnalare questa pagina come non sicura. È un indirizzo della rete locale: i sottotitoli arrivano direttamente dal computer di chi parla."
    },
    "status": {
      "waiting": "In attesa di iniziare",
      "live": "In diretta",
      "paused": "In pausa",
      "reconnecting": "Riconnessione…",
      "ended": "La condivisione è terminata"
    },
    "notice": {
      "cleared": "Chi parla ha cancellato i sottotitoli precedenti",
      "restarted": "Chi parla ha iniziato un nuovo giro"
    },
    "legend": {
      "onSite": "In presenza",
      "remote": "Da remoto"
    },
    "backToLive": "Torna alla diretta",
    "dock": {
      "textSize": "Dimensione carattere",
      "more": "Altro"
    },
    "settings": {
      "title": "Visualizzazione",
      "iRead": "Io leggo",
      "textSize": "Dimensione carattere",
      "sizes": {
        "small": "Piccola",
        "medium": "Media",
        "large": "Grande",
        "xlarge": "Molto grande"
      },
      "theme": "Colori",
      "themes": {
        "dark": "Scuro",
        "light": "Chiaro",
        "contrast": "Alto contrasto"
      },
      "completeOnly": "Solo frasi complete",
      "completeOnlyHint": "Nasconde ciò che si sta ancora dicendo",
      "keepAwake": "Mantieni lo schermo acceso",
      "save": "Salva questi sottotitoli",
      "saveHint": "Un file .txt con il contenuto di questa pagina",
      "saveButton": "Salva",
      "close": "Chiudi",
      "aiNote": "I sottotitoli sono generati dall'IA e possono contenere errori."
    },
    "shortcuts": "+ − dimensione carattere · B entrambe le lingue · F schermo intero · End torna alla diretta",
    "transcript": {
      "header": "Sottotitoli Sokuji, salvati il {{time}}"
    },
    "present": {
      "title": "Leggi i sottotitoli sul telefono o sul computer",
      "step1": "Connettiti al Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scansiona con il telefono o digita questo indirizzo su un computer",
      "step3": "Scegli la lingua che vuoi leggere",
      "noInstall": "Nessuna app, nessun accesso",
      "sameNetwork": "Questo indirizzo si apre solo sulla stessa rete",
      "androidChrome": "Chrome su Android non la apre? Consentilo in Impostazioni → App → Chrome → Autorizzazioni → Dispositivi nelle vicinanze.",
      "watching": "Spettatori: {{count}}",
      "fullscreen": "Schermo intero",
      "windowTitle": "Pagina di proiezione Sokuji",
      "ended": "La condivisione è terminata"
    }
  },
  "ja": {
    "title": "Sokuji 字幕",
    "connecting": "接続中…",
    "original": "原文",
    "enter": {
      "iRead": "読みたい言語",
      "both": "両方の言語",
      "bothHint": "{{first}}が上、{{second}}が下",
      "start": "読み始める",
      "insecureNote": "ブラウザでこのページが「安全でない」と表示される場合がありますが、これはローカルネットワークのアドレスだからです。字幕は話者のパソコンから直接届いています。"
    },
    "status": {
      "waiting": "開始待ち",
      "live": "ライブ",
      "paused": "一時停止中",
      "reconnecting": "再接続中…",
      "ended": "共有は終了しました"
    },
    "notice": {
      "cleared": "話者がこれまでの字幕を消去しました",
      "restarted": "話者が新しいセッションを開始しました"
    },
    "legend": {
      "onSite": "対面",
      "remote": "オンライン"
    },
    "backToLive": "最新に戻る",
    "dock": {
      "textSize": "文字サイズ",
      "more": "その他"
    },
    "settings": {
      "title": "表示設定",
      "iRead": "表示する言語",
      "textSize": "文字サイズ",
      "sizes": {
        "small": "小",
        "medium": "中",
        "large": "大",
        "xlarge": "特大"
      },
      "theme": "配色",
      "themes": {
        "dark": "ダーク",
        "light": "ライト",
        "contrast": "ハイコントラスト"
      },
      "completeOnly": "完成した文だけ表示",
      "completeOnlyHint": "話している途中の文は表示しません",
      "keepAwake": "画面をつけたままにする",
      "save": "この字幕を保存",
      "saveHint": "このページの字幕を .txt ファイルでダウンロードします",
      "saveButton": "保存",
      "close": "閉じる",
      "aiNote": "字幕は AI が生成しているため、誤りを含む場合があります。"
    },
    "shortcuts": "+ − 文字サイズ · B 両方の言語 · F 全画面 · End 最新に戻る",
    "transcript": {
      "header": "Sokuji 字幕（{{time}} 保存）"
    },
    "present": {
      "title": "お手元のスマートフォンやパソコンで字幕をご覧ください",
      "step1": "Wi‑Fi に接続",
      "password": "パスワード：{{password}}",
      "step2": "スマートフォンでスキャン、またはパソコンでこのアドレスを入力",
      "step3": "読みたい言語を選択",
      "noInstall": "アプリ不要・サインイン不要",
      "sameNetwork": "このアドレスは同じネットワーク内でのみ開けます",
      "androidChrome": "Android の Chrome で開けない場合は、「設定 → アプリ → Chrome → 権限 → 付近のデバイス」で許可してください。",
      "watching": "閲覧中：{{count}}",
      "fullscreen": "全画面表示",
      "windowTitle": "Sokuji 投影ページ",
      "ended": "共有は終了しました"
    }
  },
  "ko": {
    "title": "Sokuji 자막",
    "connecting": "연결 중…",
    "original": "원문",
    "enter": {
      "iRead": "읽을 언어",
      "both": "두 언어 모두",
      "bothHint": "{{first}} 위, {{second}} 아래",
      "start": "보기 시작",
      "insecureNote": "브라우저에 이 페이지가 안전하지 않다고 표시될 수 있습니다. 로컬 네트워크 주소이기 때문이며, 자막은 화자의 컴퓨터에서 바로 전송됩니다."
    },
    "status": {
      "waiting": "시작 대기 중",
      "live": "실시간",
      "paused": "일시 중지됨",
      "reconnecting": "다시 연결 중…",
      "ended": "공유가 종료되었습니다"
    },
    "notice": {
      "cleared": "화자가 이전 자막을 지웠습니다",
      "restarted": "화자가 새 세션을 시작했습니다"
    },
    "legend": {
      "onSite": "현장",
      "remote": "온라인"
    },
    "backToLive": "최신으로 이동",
    "dock": {
      "textSize": "글자 크기",
      "more": "더 보기"
    },
    "settings": {
      "title": "표시 설정",
      "iRead": "표시 언어",
      "textSize": "글자 크기",
      "sizes": {
        "small": "작게",
        "medium": "보통",
        "large": "크게",
        "xlarge": "아주 크게"
      },
      "theme": "색상 테마",
      "themes": {
        "dark": "다크",
        "light": "라이트",
        "contrast": "고대비"
      },
      "completeOnly": "완성된 문장만 표시",
      "completeOnlyHint": "아직 말하는 중인 문장은 숨깁니다",
      "keepAwake": "화면 켜짐 유지",
      "save": "이 자막 저장",
      "saveHint": "이 페이지의 내용을 .txt 파일로 저장합니다",
      "saveButton": "저장",
      "close": "닫기",
      "aiNote": "자막은 AI가 생성하므로 오류가 있을 수 있습니다."
    },
    "shortcuts": "+ − 글자 크기 · B 두 언어 · F 전체 화면 · End 최신으로 이동",
    "transcript": {
      "header": "Sokuji 자막, {{time}} 저장"
    },
    "present": {
      "title": "휴대폰이나 컴퓨터에서 자막을 보세요",
      "step1": "Wi‑Fi에 연결",
      "password": "비밀번호: {{password}}",
      "step2": "휴대폰으로 스캔하거나 컴퓨터에서 이 주소를 입력",
      "step3": "읽을 언어 선택",
      "noInstall": "앱 설치도, 로그인도 필요 없음",
      "sameNetwork": "이 주소는 같은 네트워크에서만 열립니다",
      "androidChrome": "Android Chrome에서 열리지 않나요? 설정 → 애플리케이션 → Chrome → 권한 → 근처 기기에서 허용하세요.",
      "watching": "시청 중: {{count}}",
      "fullscreen": "전체 화면",
      "windowTitle": "Sokuji 프로젝터 화면",
      "ended": "공유가 종료되었습니다"
    }
  },
  "ms": {
    "title": "Sari kata Sokuji",
    "connecting": "Menyambung…",
    "original": "Asal",
    "enter": {
      "iRead": "Saya mahu membaca",
      "both": "Kedua-dua bahasa",
      "bothHint": "{{first}} di atas, {{second}} di bawah",
      "start": "Mula membaca",
      "insecureNote": "Pelayar anda mungkin menyatakan halaman ini tidak selamat. Ini alamat rangkaian setempat: sari kata dihantar terus dari komputer penutur."
    },
    "status": {
      "waiting": "Menunggu bermula",
      "live": "Langsung",
      "paused": "Dijeda",
      "reconnecting": "Menyambung semula…",
      "ended": "Perkongsian telah tamat"
    },
    "notice": {
      "cleared": "Penutur telah mengosongkan sari kata sebelum ini",
      "restarted": "Penutur telah memulakan sesi baharu"
    },
    "legend": {
      "onSite": "Di lokasi",
      "remote": "Dalam talian"
    },
    "backToLive": "Ke terkini",
    "dock": {
      "textSize": "Saiz teks",
      "more": "Lagi"
    },
    "settings": {
      "title": "Paparan",
      "iRead": "Saya membaca",
      "textSize": "Saiz teks",
      "sizes": {
        "small": "Kecil",
        "medium": "Sederhana",
        "large": "Besar",
        "xlarge": "Sangat besar"
      },
      "theme": "Warna",
      "themes": {
        "dark": "Gelap",
        "light": "Cerah",
        "contrast": "Kontras tinggi"
      },
      "completeOnly": "Ayat lengkap sahaja",
      "completeOnlyHint": "Sembunyikan apa yang masih diucapkan",
      "keepAwake": "Pastikan skrin kekal hidup",
      "save": "Simpan sari kata ini",
      "saveHint": "Fail .txt berisi kandungan halaman ini",
      "saveButton": "Simpan",
      "close": "Tutup",
      "aiNote": "Sari kata dijana oleh AI dan mungkin mengandungi kesilapan."
    },
    "shortcuts": "+ − saiz teks · B kedua-dua bahasa · F skrin penuh · End ke terkini",
    "transcript": {
      "header": "Sari kata Sokuji, disimpan {{time}}"
    },
    "present": {
      "title": "Baca sari kata pada telefon atau komputer anda",
      "step1": "Sambung ke Wi‑Fi",
      "password": "Kata laluan: {{password}}",
      "step2": "Imbas dengan telefon, atau taip alamat ini pada komputer",
      "step3": "Pilih bahasa yang anda mahu baca",
      "noInstall": "Tiada aplikasi, tiada log masuk",
      "sameNetwork": "Alamat ini hanya boleh dibuka dalam rangkaian yang sama",
      "androidChrome": "Chrome di Android tidak dapat membukanya? Benarkan dalam Tetapan → Apl → Chrome → Kebenaran → Peranti berdekatan.",
      "watching": "Menonton: {{count}}",
      "fullscreen": "Skrin penuh",
      "windowTitle": "Halaman projektor Sokuji",
      "ended": "Perkongsian telah tamat"
    }
  },
  "nl": {
    "title": "Sokuji-ondertiteling",
    "connecting": "Verbinden…",
    "original": "Origineel",
    "enter": {
      "iRead": "Ik wil lezen",
      "both": "Beide talen",
      "bothHint": "{{first}} boven, {{second}} eronder",
      "start": "Beginnen met lezen",
      "insecureNote": "Uw browser noemt deze pagina mogelijk niet veilig. Het is een adres op het lokale netwerk: de ondertiteling komt rechtstreeks van de computer van de spreker."
    },
    "status": {
      "waiting": "Wacht op start",
      "live": "Live",
      "paused": "Gepauzeerd",
      "reconnecting": "Opnieuw verbinden…",
      "ended": "Het delen is gestopt"
    },
    "notice": {
      "cleared": "De spreker heeft de eerdere ondertiteling gewist",
      "restarted": "De spreker is een nieuwe ronde begonnen"
    },
    "legend": {
      "onSite": "Ter plaatse",
      "remote": "Online"
    },
    "backToLive": "Terug naar live",
    "dock": {
      "textSize": "Lettergrootte",
      "more": "Meer"
    },
    "settings": {
      "title": "Weergave",
      "iRead": "Ik lees",
      "textSize": "Lettergrootte",
      "sizes": {
        "small": "Klein",
        "medium": "Middel",
        "large": "Groot",
        "xlarge": "Extra groot"
      },
      "theme": "Kleuren",
      "themes": {
        "dark": "Donker",
        "light": "Licht",
        "contrast": "Hoog contrast"
      },
      "completeOnly": "Alleen volledige zinnen",
      "completeOnlyHint": "Verbergt wat nog wordt uitgesproken",
      "keepAwake": "Scherm aan laten",
      "save": "Deze ondertiteling opslaan",
      "saveHint": "Een .txt-bestand met de inhoud van deze pagina",
      "saveButton": "Opslaan",
      "close": "Sluiten",
      "aiNote": "De ondertiteling wordt door AI gemaakt en kan fouten bevatten."
    },
    "shortcuts": "+ − lettergrootte · B beide talen · F volledig scherm · End terug naar live",
    "transcript": {
      "header": "Sokuji-ondertiteling, opgeslagen op {{time}}"
    },
    "present": {
      "title": "Lees de ondertiteling op uw telefoon of computer",
      "step1": "Maak verbinding met de Wi‑Fi",
      "password": "Wachtwoord: {{password}}",
      "step2": "Scan met uw telefoon of typ dit adres op een computer",
      "step3": "Kies de taal die u wilt lezen",
      "noInstall": "Geen app, niet inloggen",
      "sameNetwork": "Dit adres werkt alleen op hetzelfde netwerk",
      "androidChrome": "Opent Chrome op Android de pagina niet? Sta het toe via Instellingen → Apps → Chrome → Rechten → Apparaten in de buurt.",
      "watching": "Kijkers: {{count}}",
      "fullscreen": "Volledig scherm",
      "windowTitle": "Sokuji-projectiepagina",
      "ended": "Het delen is gestopt"
    }
  },
  "pl": {
    "title": "Napisy Sokuji",
    "connecting": "Łączenie…",
    "original": "Oryginał",
    "enter": {
      "iRead": "Chcę czytać",
      "both": "Oba języki",
      "bothHint": "{{first}} na górze, {{second}} pod spodem",
      "start": "Zacznij czytać",
      "insecureNote": "Przeglądarka może oznaczyć tę stronę jako niezabezpieczoną. To adres w sieci lokalnej: napisy pochodzą prosto z komputera mówcy."
    },
    "status": {
      "waiting": "Oczekiwanie na start",
      "live": "Na żywo",
      "paused": "Wstrzymano",
      "reconnecting": "Ponowne łączenie…",
      "ended": "Udostępnianie zakończone"
    },
    "notice": {
      "cleared": "Mówca wyczyścił wcześniejsze napisy",
      "restarted": "Mówca rozpoczął nową rundę"
    },
    "legend": {
      "onSite": "Na miejscu",
      "remote": "Zdalnie"
    },
    "backToLive": "Wróć do bieżących",
    "dock": {
      "textSize": "Rozmiar czcionki",
      "more": "Więcej"
    },
    "settings": {
      "title": "Wyświetlanie",
      "iRead": "Ja czytam",
      "textSize": "Rozmiar czcionki",
      "sizes": {
        "small": "Mały",
        "medium": "Średni",
        "large": "Duży",
        "xlarge": "Bardzo duży"
      },
      "theme": "Kolory",
      "themes": {
        "dark": "Ciemny",
        "light": "Jasny",
        "contrast": "Wysoki kontrast"
      },
      "completeOnly": "Tylko pełne zdania",
      "completeOnlyHint": "Ukryj to, co jest jeszcze wypowiadane",
      "keepAwake": "Nie wygaszaj ekranu",
      "save": "Zapisz te napisy",
      "saveHint": "Plik .txt z zawartością tej strony",
      "saveButton": "Zapisz",
      "close": "Zamknij",
      "aiNote": "Napisy są generowane przez AI i mogą zawierać błędy."
    },
    "shortcuts": "+ − rozmiar czcionki · B oba języki · F pełny ekran · End wróć do bieżących",
    "transcript": {
      "header": "Napisy Sokuji, zapisano {{time}}"
    },
    "present": {
      "title": "Czytaj napisy na telefonie lub komputerze",
      "step1": "Połącz się z Wi‑Fi",
      "password": "Hasło: {{password}}",
      "step2": "Zeskanuj telefonem albo wpisz ten adres na komputerze",
      "step3": "Wybierz język, w którym chcesz czytać",
      "noInstall": "Bez aplikacji, bez logowania",
      "sameNetwork": "Ten adres działa tylko w tej samej sieci",
      "androidChrome": "Chrome na Androidzie nie otwiera strony? Zezwól w Ustawienia → Aplikacje → Chrome → Uprawnienia → Urządzenia w pobliżu.",
      "watching": "Oglądający: {{count}}",
      "fullscreen": "Pełny ekran",
      "windowTitle": "Strona projektora Sokuji",
      "ended": "Udostępnianie zakończone"
    }
  },
  "pt_BR": {
    "title": "Legendas do Sokuji",
    "connecting": "Conectando…",
    "original": "Original",
    "enter": {
      "iRead": "Quero ler",
      "both": "Os dois idiomas",
      "bothHint": "{{first}} em cima, {{second}} embaixo",
      "start": "Começar a ler",
      "insecureNote": "Seu navegador pode dizer que esta página não é segura. É um endereço da rede local: as legendas vêm direto do computador do apresentador."
    },
    "status": {
      "waiting": "Aguardando o início",
      "live": "Ao vivo",
      "paused": "Pausado",
      "reconnecting": "Reconectando…",
      "ended": "O compartilhamento terminou"
    },
    "notice": {
      "cleared": "O apresentador apagou as legendas anteriores",
      "restarted": "O apresentador começou de novo"
    },
    "legend": {
      "onSite": "Presencial",
      "remote": "Remoto"
    },
    "backToLive": "Voltar ao vivo",
    "dock": {
      "textSize": "Tamanho do texto",
      "more": "Mais"
    },
    "settings": {
      "title": "Exibição",
      "iRead": "Quero ler",
      "textSize": "Tamanho do texto",
      "sizes": {
        "small": "Pequeno",
        "medium": "Médio",
        "large": "Grande",
        "xlarge": "Extragrande"
      },
      "theme": "Cores",
      "themes": {
        "dark": "Escuro",
        "light": "Claro",
        "contrast": "Alto contraste"
      },
      "completeOnly": "Só frases completas",
      "completeOnlyHint": "Oculta o que ainda está sendo dito",
      "keepAwake": "Manter a tela ligada",
      "save": "Salvar estas legendas",
      "saveHint": "Um arquivo .txt com o que está nesta página",
      "saveButton": "Salvar",
      "close": "Fechar",
      "aiNote": "As legendas são geradas por IA e podem conter erros."
    },
    "shortcuts": "+ − tamanho do texto · B os dois idiomas · F tela cheia · End voltar ao vivo",
    "transcript": {
      "header": "Legendas do Sokuji, salvas em {{time}}"
    },
    "present": {
      "title": "Leia as legendas no celular ou no computador",
      "step1": "Conecte-se ao Wi‑Fi",
      "password": "Senha: {{password}}",
      "step2": "Escaneie o código com o celular ou digite este endereço no computador",
      "step3": "Escolha o idioma que você quer ler",
      "noInstall": "Sem aplicativo, sem login",
      "sameNetwork": "Este endereço só abre na mesma rede",
      "androidChrome": "O Chrome no Android não abre? Permita em Configurações → Apps → Chrome → Permissões → Dispositivos por perto.",
      "watching": "Assistindo: {{count}}",
      "fullscreen": "Tela cheia",
      "windowTitle": "Página de projeção do Sokuji",
      "ended": "O compartilhamento terminou"
    }
  },
  "pt_PT": {
    "title": "Legendas do Sokuji",
    "connecting": "A ligar…",
    "original": "Original",
    "enter": {
      "iRead": "Quero ler",
      "both": "Os dois idiomas",
      "bothHint": "{{first}} em cima, {{second}} em baixo",
      "start": "Começar a ler",
      "insecureNote": "O seu navegador pode indicar que esta página não é segura. É um endereço da rede local: as legendas vêm diretamente do computador do apresentador."
    },
    "status": {
      "waiting": "A aguardar o início",
      "live": "Em direto",
      "paused": "Em pausa",
      "reconnecting": "A restabelecer a ligação…",
      "ended": "A partilha terminou"
    },
    "notice": {
      "cleared": "O apresentador apagou as legendas anteriores",
      "restarted": "O apresentador recomeçou"
    },
    "legend": {
      "onSite": "Presencial",
      "remote": "Remoto"
    },
    "backToLive": "Voltar ao direto",
    "dock": {
      "textSize": "Tamanho do texto",
      "more": "Mais"
    },
    "settings": {
      "title": "Apresentação",
      "iRead": "Quero ler",
      "textSize": "Tamanho do texto",
      "sizes": {
        "small": "Pequeno",
        "medium": "Médio",
        "large": "Grande",
        "xlarge": "Muito grande"
      },
      "theme": "Cores",
      "themes": {
        "dark": "Escuro",
        "light": "Claro",
        "contrast": "Alto contraste"
      },
      "completeOnly": "Só frases completas",
      "completeOnlyHint": "Oculta o que ainda está a ser dito",
      "keepAwake": "Manter o ecrã ligado",
      "save": "Guardar estas legendas",
      "saveHint": "Um ficheiro .txt com o que está nesta página",
      "saveButton": "Guardar",
      "close": "Fechar",
      "aiNote": "As legendas são geradas por IA e podem conter erros."
    },
    "shortcuts": "+ − tamanho do texto · B os dois idiomas · F ecrã inteiro · End voltar ao direto",
    "transcript": {
      "header": "Legendas do Sokuji, guardadas em {{time}}"
    },
    "present": {
      "title": "Leia as legendas no telemóvel ou no computador",
      "step1": "Ligue-se ao Wi‑Fi",
      "password": "Palavra-passe: {{password}}",
      "step2": "Leia o código com o telemóvel ou escreva este endereço no computador",
      "step3": "Escolha o idioma que quer ler",
      "noInstall": "Sem aplicação nem início de sessão",
      "sameNetwork": "Este endereço só abre na mesma rede",
      "androidChrome": "O Chrome no Android não abre? Permita em Definições → Apps → Chrome → Autorizações → Dispositivos próximos.",
      "watching": "A ver: {{count}}",
      "fullscreen": "Ecrã inteiro",
      "windowTitle": "Página de projeção do Sokuji",
      "ended": "A partilha terminou"
    }
  },
  "ru": {
    "title": "Субтитры Sokuji",
    "connecting": "Подключение…",
    "original": "Оригинал",
    "enter": {
      "iRead": "Хочу читать",
      "both": "Оба языка",
      "bothHint": "Сверху {{first}}, снизу {{second}}",
      "start": "Начать чтение",
      "insecureNote": "Браузер может назвать эту страницу небезопасной. Это адрес в локальной сети: субтитры приходят прямо с компьютера выступающего."
    },
    "status": {
      "waiting": "Ожидание начала",
      "live": "В эфире",
      "paused": "Пауза",
      "reconnecting": "Переподключение…",
      "ended": "Показ завершён"
    },
    "notice": {
      "cleared": "Выступающий очистил предыдущие субтитры",
      "restarted": "Выступающий начал заново"
    },
    "legend": {
      "onSite": "Очно",
      "remote": "Онлайн"
    },
    "backToLive": "К прямому эфиру",
    "dock": {
      "textSize": "Размер текста",
      "more": "Ещё"
    },
    "settings": {
      "title": "Отображение",
      "iRead": "Хочу читать",
      "textSize": "Размер текста",
      "sizes": {
        "small": "Мелкий",
        "medium": "Средний",
        "large": "Крупный",
        "xlarge": "Очень крупный"
      },
      "theme": "Оформление",
      "themes": {
        "dark": "Тёмное",
        "light": "Светлое",
        "contrast": "Высокий контраст"
      },
      "completeOnly": "Только законченные фразы",
      "completeOnlyHint": "Скрывать то, что ещё произносится",
      "keepAwake": "Не выключать экран",
      "save": "Сохранить эти субтитры",
      "saveHint": "Файл .txt со всем, что есть на этой странице",
      "saveButton": "Сохранить",
      "close": "Закрыть",
      "aiNote": "Субтитры создаёт ИИ, поэтому в них возможны ошибки."
    },
    "shortcuts": "+ − размер текста · B оба языка · F полный экран · End к прямому эфиру",
    "transcript": {
      "header": "Субтитры Sokuji, сохранены {{time}}"
    },
    "present": {
      "title": "Читайте субтитры на телефоне или компьютере",
      "step1": "Подключитесь к Wi‑Fi",
      "password": "Пароль: {{password}}",
      "step2": "Отсканируйте код телефоном или введите этот адрес на компьютере",
      "step3": "Выберите язык, на котором хотите читать",
      "noInstall": "Без приложения и без входа",
      "sameNetwork": "Этот адрес открывается только в той же сети",
      "androidChrome": "Chrome на Android не открывает страницу? Разрешите в Настройки → Приложения → Chrome → Разрешения → Устройства поблизости.",
      "watching": "Смотрят: {{count}}",
      "fullscreen": "Полный экран",
      "windowTitle": "Sokuji — страница для проектора",
      "ended": "Показ завершён"
    }
  },
  "sv": {
    "title": "Sokuji-undertexter",
    "connecting": "Ansluter…",
    "original": "Original",
    "enter": {
      "iRead": "Jag vill läsa",
      "both": "Båda språken",
      "bothHint": "{{first}} överst, {{second}} under",
      "start": "Börja läsa",
      "insecureNote": "Webbläsaren kan kalla den här sidan osäker. Det är en adress i det lokala nätverket: undertexterna kommer direkt från talarens dator."
    },
    "status": {
      "waiting": "Väntar på start",
      "live": "Live",
      "paused": "Pausad",
      "reconnecting": "Ansluter igen…",
      "ended": "Delningen har avslutats"
    },
    "notice": {
      "cleared": "Talaren har rensat de tidigare undertexterna",
      "restarted": "Talaren har startat en ny omgång"
    },
    "legend": {
      "onSite": "På plats",
      "remote": "På distans"
    },
    "backToLive": "Tillbaka till live",
    "dock": {
      "textSize": "Textstorlek",
      "more": "Mer"
    },
    "settings": {
      "title": "Visning",
      "iRead": "Jag läser",
      "textSize": "Textstorlek",
      "sizes": {
        "small": "Liten",
        "medium": "Mellan",
        "large": "Stor",
        "xlarge": "Extra stor"
      },
      "theme": "Färger",
      "themes": {
        "dark": "Mörkt",
        "light": "Ljust",
        "contrast": "Hög kontrast"
      },
      "completeOnly": "Bara hela meningar",
      "completeOnlyHint": "Dölj det som fortfarande sägs",
      "keepAwake": "Håll skärmen tänd",
      "save": "Spara de här undertexterna",
      "saveHint": "En .txt-fil med det som finns på sidan",
      "saveButton": "Spara",
      "close": "Stäng",
      "aiNote": "Undertexterna skapas av AI och kan innehålla fel."
    },
    "shortcuts": "+ − textstorlek · B båda språken · F helskärm · End tillbaka till live",
    "transcript": {
      "header": "Sokuji-undertexter, sparade {{time}}"
    },
    "present": {
      "title": "Läs undertexterna i din telefon eller dator",
      "step1": "Anslut till Wi‑Fi-nätverket",
      "password": "Lösenord: {{password}}",
      "step2": "Skanna med telefonen eller skriv in adressen på en dator",
      "step3": "Välj språket du vill läsa",
      "noInstall": "Ingen app, ingen inloggning",
      "sameNetwork": "Adressen fungerar bara i samma nätverk",
      "androidChrome": "Öppnar inte Chrome på Android sidan? Tillåt det i Inställningar → Appar → Chrome → Behörigheter → Enheter i närheten.",
      "watching": "Tittare: {{count}}",
      "fullscreen": "Helskärm",
      "windowTitle": "Sokujis projektorsida",
      "ended": "Delningen har avslutats"
    }
  },
  "ta": {
    "title": "Sokuji துணைத்தலைப்புகள்",
    "connecting": "இணைக்கிறது…",
    "original": "மூலம்",
    "enter": {
      "iRead": "நான் படிக்க விரும்புவது",
      "both": "இரு மொழிகளும்",
      "bothHint": "மேலே {{first}}, கீழே {{second}}",
      "start": "படிக்கத் தொடங்கு",
      "insecureNote": "உங்கள் உலாவி இந்தப் பக்கத்தைப் பாதுகாப்பற்றது எனக் காட்டலாம். இது உள்ளூர் நெட்வொர்க் முகவரி: துணைத்தலைப்புகள் பேசுபவரின் கணினியிலிருந்து நேரடியாக வருகின்றன."
    },
    "status": {
      "waiting": "தொடங்கக் காத்திருக்கிறது",
      "live": "நேரலை",
      "paused": "இடைநிறுத்தப்பட்டது",
      "reconnecting": "மீண்டும் இணைக்கிறது…",
      "ended": "பகிர்வு முடிந்தது"
    },
    "notice": {
      "cleared": "பேசுபவர் முந்தைய துணைத்தலைப்புகளை அழித்தார்",
      "restarted": "பேசுபவர் புதிய சுற்றைத் தொடங்கினார்"
    },
    "legend": {
      "onSite": "நேரில்",
      "remote": "ஆன்லைன்"
    },
    "backToLive": "நேரலைக்குத் திரும்பு",
    "dock": {
      "textSize": "எழுத்தளவு",
      "more": "மேலும்"
    },
    "settings": {
      "title": "காட்சி அமைப்புகள்",
      "iRead": "படிக்கும் மொழி",
      "textSize": "எழுத்தளவு",
      "sizes": {
        "small": "சிறியது",
        "medium": "நடுத்தரம்",
        "large": "பெரியது",
        "xlarge": "மிகப் பெரியது"
      },
      "theme": "வண்ணங்கள்",
      "themes": {
        "dark": "இருண்ட",
        "light": "வெளிர்",
        "contrast": "உயர் மாறுபாடு"
      },
      "completeOnly": "முழு வாக்கியங்கள் மட்டும்",
      "completeOnlyHint": "இன்னும் பேசப்பட்டுக்கொண்டிருப்பதை மறை",
      "keepAwake": "திரையை அணையாமல் வை",
      "save": "இந்தத் துணைத்தலைப்புகளைச் சேமி",
      "saveHint": "இந்தப் பக்கத்தில் உள்ளவை அடங்கிய .txt கோப்பு",
      "saveButton": "சேமி",
      "close": "மூடு",
      "aiNote": "துணைத்தலைப்புகள் AI மூலம் உருவாக்கப்படுகின்றன; அவற்றில் பிழைகள் இருக்கலாம்."
    },
    "shortcuts": "+ − எழுத்தளவு · B இரு மொழிகளும் · F முழுத்திரை · End நேரலைக்குத் திரும்பு",
    "transcript": {
      "header": "Sokuji துணைத்தலைப்புகள், சேமித்தது: {{time}}"
    },
    "present": {
      "title": "உங்கள் ஃபோனிலோ கணினியிலோ துணைத்தலைப்புகளைப் படியுங்கள்",
      "step1": "Wi‑Fi-இல் இணையுங்கள்",
      "password": "கடவுச்சொல்: {{password}}",
      "step2": "ஃபோனில் ஸ்கேன் செய்யுங்கள், அல்லது கணினியில் இந்த முகவரியை உள்ளிடுங்கள்",
      "step3": "நீங்கள் படிக்க விரும்பும் மொழியைத் தேர்ந்தெடுங்கள்",
      "noInstall": "பயன்பாடும் தேவையில்லை, உள்நுழைவும் தேவையில்லை",
      "sameNetwork": "இந்த முகவரி அதே நெட்வொர்க்கில் மட்டுமே திறக்கும்",
      "androidChrome": "Android-இல் Chrome திறக்கவில்லையா? அமைப்புகள் → ஆப்ஸ் → Chrome → அனுமதிகள் → அருகிலுள்ள சாதனங்கள் என்பதில் அனுமதியுங்கள்.",
      "watching": "பார்ப்பவர்கள்: {{count}}",
      "fullscreen": "முழுத்திரை",
      "windowTitle": "Sokuji புரொஜெக்டர் பக்கம்",
      "ended": "பகிர்வு முடிந்தது"
    }
  },
  "te": {
    "title": "Sokuji సబ్‌టైటిల్స్",
    "connecting": "కనెక్ట్ అవుతోంది…",
    "original": "మూలం",
    "enter": {
      "iRead": "నేను చదవాలనుకుంటున్నది",
      "both": "రెండు భాషలూ",
      "bothHint": "పైన {{first}}, కింద {{second}}",
      "start": "చదవడం ప్రారంభించండి",
      "insecureNote": "మీ బ్రౌజర్ ఈ పేజీని సురక్షితం కానిదిగా చూపవచ్చు. ఇది లోకల్ నెట్‌వర్క్ చిరునామా: సబ్‌టైటిల్స్ నేరుగా మాట్లాడేవారి కంప్యూటర్ నుంచి వస్తాయి."
    },
    "status": {
      "waiting": "ప్రారంభం కోసం వేచి ఉంది",
      "live": "లైవ్",
      "paused": "పాజ్ అయింది",
      "reconnecting": "మళ్లీ కనెక్ట్ అవుతోంది…",
      "ended": "షేరింగ్ ముగిసింది"
    },
    "notice": {
      "cleared": "మాట్లాడేవారు మునుపటి సబ్‌టైటిల్స్‌ను క్లియర్ చేశారు",
      "restarted": "మాట్లాడేవారు కొత్త రౌండ్ ప్రారంభించారు"
    },
    "legend": {
      "onSite": "ప్రత్యక్షంగా",
      "remote": "ఆన్‌లైన్"
    },
    "backToLive": "లైవ్‌కు తిరిగి వెళ్ళు",
    "dock": {
      "textSize": "అక్షర పరిమాణం",
      "more": "మరిన్ని"
    },
    "settings": {
      "title": "ప్రదర్శన సెట్టింగ్‌లు",
      "iRead": "చదివే భాష",
      "textSize": "అక్షర పరిమాణం",
      "sizes": {
        "small": "చిన్నది",
        "medium": "మధ్యస్థం",
        "large": "పెద్దది",
        "xlarge": "చాలా పెద్దది"
      },
      "theme": "రంగులు",
      "themes": {
        "dark": "డార్క్",
        "light": "లైట్",
        "contrast": "హై కాంట్రాస్ట్"
      },
      "completeOnly": "పూర్తి వాక్యాలు మాత్రమే",
      "completeOnlyHint": "ఇంకా మాట్లాడుతున్న భాగాన్ని దాచు",
      "keepAwake": "స్క్రీన్‌ను ఆన్‌లో ఉంచు",
      "save": "ఈ సబ్‌టైటిల్స్‌ను సేవ్ చేయి",
      "saveHint": "ఈ పేజీలో ఉన్నదంతా ఒక .txt ఫైల్‌గా",
      "saveButton": "సేవ్ చేయి",
      "close": "మూసివేయి",
      "aiNote": "సబ్‌టైటిల్స్ AI ద్వారా రూపొందుతాయి, వాటిలో తప్పులు ఉండవచ్చు."
    },
    "shortcuts": "+ − అక్షర పరిమాణం · B రెండు భాషలూ · F పూర్తి స్క్రీన్ · End లైవ్‌కు తిరిగి వెళ్ళు",
    "transcript": {
      "header": "Sokuji సబ్‌టైటిల్స్, సేవ్ చేసిన సమయం {{time}}"
    },
    "present": {
      "title": "మీ ఫోన్ లేదా కంప్యూటర్‌లో సబ్‌టైటిల్స్ చదవండి",
      "step1": "Wi‑Fiకి కనెక్ట్ అవ్వండి",
      "password": "పాస్వర్డ్: {{password}}",
      "step2": "ఫోన్‌తో స్కాన్ చేయండి, లేదా కంప్యూటర్‌లో ఈ చిరునామాను టైప్ చేయండి",
      "step3": "మీరు చదవాలనుకునే భాషను ఎంచుకోండి",
      "noInstall": "యాప్ అవసరం లేదు, సైన్ ఇన్ అవసరం లేదు",
      "sameNetwork": "ఈ చిరునామా అదే నెట్‌వర్క్‌లో మాత్రమే తెరుచుకుంటుంది",
      "androidChrome": "Android‌లో Chrome తెరవడం లేదా? సెట్టింగ్‌లు → యాప్‌లు → Chrome → అనుమతులు → సమీపంలోని పరికరాలు‌లో అనుమతించండి.",
      "watching": "చూస్తున్నవారు: {{count}}",
      "fullscreen": "పూర్తి స్క్రీన్",
      "windowTitle": "Sokuji ప్రొజెక్టర్ పేజీ",
      "ended": "షేరింగ్ ముగిసింది"
    }
  },
  "th": {
    "title": "คำบรรยาย Sokuji",
    "connecting": "กำลังเชื่อมต่อ…",
    "original": "ต้นฉบับ",
    "enter": {
      "iRead": "ภาษาที่ต้องการอ่าน",
      "both": "ทั้งสองภาษา",
      "bothHint": "{{first}} ด้านบน {{second}} ด้านล่าง",
      "start": "เริ่มอ่าน",
      "insecureNote": "เบราว์เซอร์อาจแจ้งว่าหน้านี้ไม่ปลอดภัย เพราะเป็นที่อยู่ในเครือข่ายภายใน คำบรรยายส่งตรงมาจากคอมพิวเตอร์ของผู้พูด"
    },
    "status": {
      "waiting": "รอเริ่ม",
      "live": "สด",
      "paused": "หยุดชั่วคราว",
      "reconnecting": "กำลังเชื่อมต่อใหม่…",
      "ended": "การแชร์สิ้นสุดแล้ว"
    },
    "notice": {
      "cleared": "ผู้พูดล้างคำบรรยายก่อนหน้าแล้ว",
      "restarted": "ผู้พูดเริ่มรอบใหม่แล้ว"
    },
    "legend": {
      "onSite": "ในสถานที่",
      "remote": "ออนไลน์"
    },
    "backToLive": "ไปที่ล่าสุด",
    "dock": {
      "textSize": "ขนาดตัวอักษร",
      "more": "เพิ่มเติม"
    },
    "settings": {
      "title": "การแสดงผล",
      "iRead": "ภาษาที่อ่าน",
      "textSize": "ขนาดตัวอักษร",
      "sizes": {
        "small": "เล็ก",
        "medium": "กลาง",
        "large": "ใหญ่",
        "xlarge": "ใหญ่พิเศษ"
      },
      "theme": "ชุดสี",
      "themes": {
        "dark": "มืด",
        "light": "สว่าง",
        "contrast": "คอนทราสต์สูง"
      },
      "completeOnly": "แสดงเฉพาะประโยคที่สมบูรณ์",
      "completeOnlyHint": "ซ่อนส่วนที่ยังพูดไม่จบ",
      "keepAwake": "ให้หน้าจอเปิดค้างไว้",
      "save": "บันทึกคำบรรยายนี้",
      "saveHint": "ไฟล์ .txt ของเนื้อหาในหน้านี้",
      "saveButton": "บันทึก",
      "close": "ปิด",
      "aiNote": "คำบรรยายสร้างโดย AI และอาจมีข้อผิดพลาด"
    },
    "shortcuts": "+ − ขนาดตัวอักษร · B ทั้งสองภาษา · F เต็มหน้าจอ · End ไปที่ล่าสุด",
    "transcript": {
      "header": "คำบรรยาย Sokuji บันทึกเมื่อ {{time}}"
    },
    "present": {
      "title": "อ่านคำบรรยายบนโทรศัพท์หรือคอมพิวเตอร์ของคุณ",
      "step1": "เชื่อมต่อ Wi‑Fi",
      "password": "รหัสผ่าน: {{password}}",
      "step2": "สแกนด้วยโทรศัพท์ หรือพิมพ์ที่อยู่นี้บนคอมพิวเตอร์",
      "step3": "เลือกภาษาที่ต้องการอ่าน",
      "noInstall": "ไม่ต้องติดตั้งแอป ไม่ต้องเข้าสู่ระบบ",
      "sameNetwork": "ที่อยู่นี้เปิดได้เฉพาะในเครือข่ายเดียวกัน",
      "androidChrome": "Chrome บน Android เปิดไม่ได้ใช่ไหม อนุญาตได้ที่ การตั้งค่า → แอป → Chrome → สิทธิ์ → อุปกรณ์ที่อยู่ใกล้เคียง",
      "watching": "กำลังดู: {{count}}",
      "fullscreen": "เต็มหน้าจอ",
      "windowTitle": "หน้าโปรเจกเตอร์ Sokuji",
      "ended": "การแชร์สิ้นสุดแล้ว"
    }
  },
  "tr": {
    "title": "Sokuji altyazıları",
    "connecting": "Bağlanıyor…",
    "original": "Orijinal",
    "enter": {
      "iRead": "Ne okumak istiyorsunuz?",
      "both": "Her iki dil",
      "bothHint": "Üstte {{first}}, altta {{second}}",
      "start": "Okumaya başla",
      "insecureNote": "Tarayıcınız bu sayfayı güvenli değil olarak gösterebilir. Bu bir yerel ağ adresidir: altyazılar doğrudan konuşmacının bilgisayarından gelir."
    },
    "status": {
      "waiting": "Başlaması bekleniyor",
      "live": "Canlı",
      "paused": "Duraklatıldı",
      "reconnecting": "Yeniden bağlanıyor…",
      "ended": "Paylaşım sona erdi"
    },
    "notice": {
      "cleared": "Konuşmacı önceki altyazıları temizledi",
      "restarted": "Konuşmacı baştan başladı"
    },
    "legend": {
      "onSite": "Yüz yüze",
      "remote": "Çevrim içi"
    },
    "backToLive": "Canlıya dön",
    "dock": {
      "textSize": "Metin boyutu",
      "more": "Daha fazla"
    },
    "settings": {
      "title": "Görünüm",
      "iRead": "Okuma dili",
      "textSize": "Metin boyutu",
      "sizes": {
        "small": "Küçük",
        "medium": "Orta",
        "large": "Büyük",
        "xlarge": "Çok büyük"
      },
      "theme": "Renkler",
      "themes": {
        "dark": "Koyu",
        "light": "Açık",
        "contrast": "Yüksek kontrast"
      },
      "completeOnly": "Yalnızca tamamlanmış cümleler",
      "completeOnlyHint": "Hâlâ söylenmekte olanı gizle",
      "keepAwake": "Ekranı açık tut",
      "save": "Bu altyazıları kaydet",
      "saveHint": "Bu sayfadakileri içeren bir .txt dosyası",
      "saveButton": "Kaydet",
      "close": "Kapat",
      "aiNote": "Altyazılar yapay zeka tarafından oluşturulur ve hata içerebilir."
    },
    "shortcuts": "+ − metin boyutu · B her iki dil · F tam ekran · End canlıya dön",
    "transcript": {
      "header": "Sokuji altyazıları, kaydedilme zamanı: {{time}}"
    },
    "present": {
      "title": "Altyazıları telefonunuzda veya bilgisayarınızda okuyun",
      "step1": "Wi‑Fi ağına bağlanın",
      "password": "Şifre: {{password}}",
      "step2": "Telefonunuzla kodu tarayın veya bilgisayarda bu adresi yazın",
      "step3": "Okumak istediğiniz dili seçin",
      "noInstall": "Uygulama ya da giriş gerekmez",
      "sameNetwork": "Bu adres yalnızca aynı ağda açılır",
      "androidChrome": "Android'de Chrome açmıyor mu? Ayarlar → Uygulamalar → Chrome → İzinler → Yakındaki cihazlar bölümünden izin verin.",
      "watching": "İzleyen: {{count}}",
      "fullscreen": "Tam ekran",
      "windowTitle": "Sokuji projeksiyon sayfası",
      "ended": "Paylaşım sona erdi"
    }
  },
  "uk": {
    "title": "Субтитри Sokuji",
    "connecting": "Підключення…",
    "original": "Оригінал",
    "enter": {
      "iRead": "Хочу читати",
      "both": "Обидві мови",
      "bothHint": "Зверху {{first}}, знизу {{second}}",
      "start": "Почати читання",
      "insecureNote": "Браузер може назвати цю сторінку незахищеною. Це адреса в локальній мережі: субтитри надходять просто з комп'ютера доповідача."
    },
    "status": {
      "waiting": "Очікування початку",
      "live": "В ефірі",
      "paused": "Пауза",
      "reconnecting": "Повторне підключення…",
      "ended": "Показ завершено"
    },
    "notice": {
      "cleared": "Доповідач очистив попередні субтитри",
      "restarted": "Доповідач почав заново"
    },
    "legend": {
      "onSite": "Очно",
      "remote": "Онлайн"
    },
    "backToLive": "До прямого ефіру",
    "dock": {
      "textSize": "Розмір тексту",
      "more": "Ще"
    },
    "settings": {
      "title": "Відображення",
      "iRead": "Хочу читати",
      "textSize": "Розмір тексту",
      "sizes": {
        "small": "Малий",
        "medium": "Середній",
        "large": "Великий",
        "xlarge": "Дуже великий"
      },
      "theme": "Оформлення",
      "themes": {
        "dark": "Темне",
        "light": "Світле",
        "contrast": "Висока контрастність"
      },
      "completeOnly": "Лише завершені фрази",
      "completeOnlyHint": "Приховувати те, що ще промовляється",
      "keepAwake": "Не вимикати екран",
      "save": "Зберегти ці субтитри",
      "saveHint": "Файл .txt з усім, що є на цій сторінці",
      "saveButton": "Зберегти",
      "close": "Закрити",
      "aiNote": "Субтитри створює ШІ, тому в них можливі помилки."
    },
    "shortcuts": "+ − розмір тексту · B обидві мови · F повний екран · End до прямого ефіру",
    "transcript": {
      "header": "Субтитри Sokuji, збережено {{time}}"
    },
    "present": {
      "title": "Читайте субтитри на телефоні чи комп'ютері",
      "step1": "Підключіться до Wi‑Fi",
      "password": "Пароль: {{password}}",
      "step2": "Відскануйте код телефоном або введіть цю адресу на комп'ютері",
      "step3": "Виберіть мову, якою хочете читати",
      "noInstall": "Без застосунку й без входу",
      "sameNetwork": "Ця адреса відкривається лише в тій самій мережі",
      "androidChrome": "Chrome на Android не відкриває сторінку? Дозвольте в Налаштування → Додатки → Chrome → Дозволи → Пристрої поблизу.",
      "watching": "Дивляться: {{count}}",
      "fullscreen": "Повний екран",
      "windowTitle": "Sokuji — сторінка для проєктора",
      "ended": "Показ завершено"
    }
  },
  "vi": {
    "title": "Phụ đề Sokuji",
    "connecting": "Đang kết nối…",
    "original": "Bản gốc",
    "enter": {
      "iRead": "Tôi muốn đọc",
      "both": "Cả hai ngôn ngữ",
      "bothHint": "{{first}} ở trên, {{second}} ở dưới",
      "start": "Bắt đầu đọc",
      "insecureNote": "Trình duyệt có thể báo trang này không an toàn. Đây là địa chỉ mạng nội bộ: phụ đề được gửi thẳng từ máy tính của người nói."
    },
    "status": {
      "waiting": "Đang chờ bắt đầu",
      "live": "Trực tiếp",
      "paused": "Đã tạm dừng",
      "reconnecting": "Đang kết nối lại…",
      "ended": "Đã kết thúc chia sẻ"
    },
    "notice": {
      "cleared": "Người nói đã xóa các phụ đề trước đó",
      "restarted": "Người nói đã bắt đầu một lượt mới"
    },
    "legend": {
      "onSite": "Tại chỗ",
      "remote": "Trực tuyến"
    },
    "backToLive": "Về mới nhất",
    "dock": {
      "textSize": "Cỡ chữ",
      "more": "Thêm"
    },
    "settings": {
      "title": "Hiển thị",
      "iRead": "Ngôn ngữ đọc",
      "textSize": "Cỡ chữ",
      "sizes": {
        "small": "Nhỏ",
        "medium": "Vừa",
        "large": "Lớn",
        "xlarge": "Rất lớn"
      },
      "theme": "Màu giao diện",
      "themes": {
        "dark": "Tối",
        "light": "Sáng",
        "contrast": "Tương phản cao"
      },
      "completeOnly": "Chỉ hiện câu hoàn chỉnh",
      "completeOnlyHint": "Ẩn phần vẫn đang được nói",
      "keepAwake": "Giữ màn hình luôn sáng",
      "save": "Lưu phụ đề này",
      "saveHint": "Tệp .txt chứa nội dung trên trang này",
      "saveButton": "Lưu",
      "close": "Đóng",
      "aiNote": "Phụ đề do AI tạo và có thể có sai sót."
    },
    "shortcuts": "+ − cỡ chữ · B hai ngôn ngữ · F toàn màn hình · End về mới nhất",
    "transcript": {
      "header": "Phụ đề Sokuji, lưu lúc {{time}}"
    },
    "present": {
      "title": "Đọc phụ đề trên điện thoại hoặc máy tính của bạn",
      "step1": "Kết nối Wi‑Fi",
      "password": "Mật khẩu: {{password}}",
      "step2": "Quét bằng điện thoại, hoặc nhập địa chỉ này trên máy tính",
      "step3": "Chọn ngôn ngữ bạn muốn đọc",
      "noInstall": "Không cần cài ứng dụng, không cần đăng nhập",
      "sameNetwork": "Địa chỉ này chỉ mở được trong cùng mạng",
      "androidChrome": "Chrome trên Android không mở được? Hãy cho phép trong Cài đặt → Ứng dụng → Chrome → Quyền → Thiết bị ở gần.",
      "watching": "Đang xem: {{count}}",
      "fullscreen": "Toàn màn hình",
      "windowTitle": "Trang trình chiếu Sokuji",
      "ended": "Đã kết thúc chia sẻ"
    }
  },
  "zh_CN": {
    "title": "Sokuji 字幕",
    "connecting": "正在连接…",
    "original": "原文",
    "enter": {
      "iRead": "我看",
      "both": "双语",
      "bothHint": "{{first}}在上，{{second}}在下",
      "start": "开始看",
      "insecureNote": "地址栏可能显示「不安全」，因为这是局域网地址：字幕直接来自讲者的电脑。"
    },
    "status": {
      "waiting": "等待开始",
      "live": "直播中",
      "paused": "已暂停",
      "reconnecting": "重新连接中…",
      "ended": "分享已结束"
    },
    "notice": {
      "cleared": "讲者清空了之前的字幕",
      "restarted": "讲者开始了新的一轮"
    },
    "legend": {
      "onSite": "现场",
      "remote": "线上"
    },
    "backToLive": "回到当前",
    "dock": {
      "textSize": "字号",
      "more": "更多"
    },
    "settings": {
      "title": "显示设置",
      "iRead": "我看",
      "textSize": "字号",
      "sizes": {
        "small": "小",
        "medium": "中",
        "large": "大",
        "xlarge": "特大"
      },
      "theme": "配色",
      "themes": {
        "dark": "深色",
        "light": "浅色",
        "contrast": "高对比"
      },
      "completeOnly": "只显示完整句",
      "completeOnlyHint": "还没说完的句子先不显示",
      "keepAwake": "保持屏幕常亮",
      "save": "保存本场字幕",
      "saveHint": "把这个页面上的字幕下载为 .txt 文件",
      "saveButton": "保存",
      "close": "关闭",
      "aiNote": "字幕由 AI 生成，仅供参考。"
    },
    "shortcuts": "+ − 字号 · B 双语 · F 全屏 · End 回到当前",
    "transcript": {
      "header": "Sokuji 字幕，保存于 {{time}}"
    },
    "present": {
      "title": "用手机或电脑看字幕",
      "step1": "连上 Wi‑Fi",
      "password": "密码：{{password}}",
      "step2": "手机扫码；电脑在浏览器输入这个地址",
      "step3": "选你要看的语言",
      "noInstall": "不用装 app，不用登录",
      "sameNetwork": "这个地址只在同一个网络里打得开",
      "androidChrome": "安卓 Chrome 打不开？在「设置 → 应用 → Chrome → 权限 → 附近设备」里允许。",
      "watching": "在看：{{count}}",
      "fullscreen": "全屏",
      "windowTitle": "Sokuji 投屏页",
      "ended": "分享已结束"
    }
  },
  "zh_TW": {
    "title": "Sokuji 字幕",
    "connecting": "正在連線…",
    "original": "原文",
    "enter": {
      "iRead": "我看",
      "both": "雙語",
      "bothHint": "{{first}}在上，{{second}}在下",
      "start": "開始看",
      "insecureNote": "網址列可能顯示「不安全」，因為這是區域網路的網址：字幕直接來自講者的電腦。"
    },
    "status": {
      "waiting": "等待開始",
      "live": "直播中",
      "paused": "已暫停",
      "reconnecting": "重新連線中…",
      "ended": "分享已結束"
    },
    "notice": {
      "cleared": "講者清除了之前的字幕",
      "restarted": "講者開始了新的一輪"
    },
    "legend": {
      "onSite": "現場",
      "remote": "線上"
    },
    "backToLive": "回到最新",
    "dock": {
      "textSize": "字級",
      "more": "更多"
    },
    "settings": {
      "title": "顯示設定",
      "iRead": "我看",
      "textSize": "字級",
      "sizes": {
        "small": "小",
        "medium": "中",
        "large": "大",
        "xlarge": "特大"
      },
      "theme": "配色",
      "themes": {
        "dark": "深色",
        "light": "淺色",
        "contrast": "高對比"
      },
      "completeOnly": "只顯示完整句子",
      "completeOnlyHint": "還沒說完的句子先不顯示",
      "keepAwake": "保持螢幕常亮",
      "save": "儲存本場字幕",
      "saveHint": "把這個頁面上的字幕下載為 .txt 檔案",
      "saveButton": "儲存",
      "close": "關閉",
      "aiNote": "字幕由 AI 產生，僅供參考。"
    },
    "shortcuts": "+ − 字級 · B 雙語 · F 全螢幕 · End 回到最新",
    "transcript": {
      "header": "Sokuji 字幕，儲存於 {{time}}"
    },
    "present": {
      "title": "用手機或電腦看字幕",
      "step1": "連上 Wi‑Fi",
      "password": "密碼：{{password}}",
      "step2": "手機掃描 QR 碼；電腦在瀏覽器輸入這個網址",
      "step3": "選擇要看的語言",
      "noInstall": "不用安裝 App，不用登入",
      "sameNetwork": "這個網址只有在同一個網路裡才打得開",
      "androidChrome": "Android 的 Chrome 打不開？請到「設定 → 應用程式 → Chrome → 權限 → 鄰近裝置」中允許。",
      "watching": "在看：{{count}}",
      "fullscreen": "全螢幕",
      "windowTitle": "Sokuji 投影頁",
      "ended": "分享已結束"
    }
  }
};
