// Generated by scripts/gen-viewer-strings.mjs from src/locales/*/translation.json.
// Do not edit: change the catalogs, then run `node scripts/gen-viewer-strings.mjs`.
export const VIEWER_WORDS: Record<string, unknown> = {
  "ar": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "bn": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "de": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "en": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "es": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "fa": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "fi": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "fil": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "fr": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "he": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "hi": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "id": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "it": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "ja": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "ko": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "ms": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "nl": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "pl": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "pt_BR": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "pt_PT": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "ru": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "sv": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "ta": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "te": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "th": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "tr": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "uk": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "vi": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "zh_CN": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  },
  "zh_TW": {
    "title": "Sokuji captions",
    "connecting": "Connecting…",
    "original": "Original",
    "enter": {
      "iRead": "I want to read",
      "both": "Both languages",
      "bothHint": "{{first}} first, {{second}} below",
      "start": "Start reading",
      "insecureNote": "Your browser may call this page not secure. It is a local network address: the captions come straight from the speaker's computer."
    },
    "status": {
      "waiting": "Waiting to start",
      "live": "Live",
      "paused": "Paused",
      "reconnecting": "Reconnecting…",
      "ended": "Sharing has ended"
    },
    "notice": {
      "cleared": "The speaker cleared the earlier captions",
      "restarted": "The speaker started a new round"
    },
    "legend": {
      "onSite": "On site",
      "remote": "Remote"
    },
    "backToLive": "Back to live",
    "dock": {
      "view": "View",
      "textSize": "Text size",
      "more": "More"
    },
    "settings": {
      "title": "Display",
      "iRead": "I read",
      "textSize": "Text size",
      "sizes": {
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "xlarge": "Extra large"
      },
      "theme": "Colors",
      "themes": {
        "dark": "Dark",
        "light": "Light",
        "contrast": "High contrast"
      },
      "completeOnly": "Only complete sentences",
      "completeOnlyHint": "Hide what is still being said",
      "keepAwake": "Keep the screen on",
      "save": "Save these captions",
      "saveHint": "A .txt file with what is on this page",
      "saveButton": "Save",
      "close": "Close",
      "aiNote": "Captions are generated by AI and may contain mistakes."
    },
    "shortcuts": "+ − text size · B both languages · F full screen · End back to live",
    "transcript": {
      "header": "Sokuji captions, saved {{time}}"
    },
    "present": {
      "title": "Read the captions on your phone or computer",
      "step1": "Join the Wi‑Fi",
      "password": "Password: {{password}}",
      "step2": "Scan with your phone, or type this address on a computer",
      "step3": "Choose the language you want to read",
      "noInstall": "No app, no sign-in",
      "sameNetwork": "This address only opens on the same network",
      "watching": "Watching: {{count}}",
      "fullscreen": "Full screen",
      "windowTitle": "Sokuji projector page",
      "ended": "Sharing has ended"
    }
  }
};
