"""Bake native/src/ops/*.ops into one C++ translation unit (parsed at first use by
sk_ops_parse, so the text format stays the single source of truth) and emit one static_assert
per recording that its expansion over the widest set a query can ask fits SK_OP_COVERAGE_MAX.
usage: gen_ops_data.py <ops-dir> <out.cpp> <sk_ops_data.h path>
       gen_ops_data.py --report <ops-dir> <sokuji_native.h path>
--report runs the same arithmetic and generates nothing: one line per recording, and exit 1
when any exceeds the SK_OP_COVERAGE_MAX the header defines. It is the check to run on a new
.ops before committing it; the build only finds out at the static_assert."""
import pathlib
import re
import sys

WIDEST_FALLBACK = 7   # len(RUNG_FALLBACK_DTYPES["q4_k_m"]) in sidecar/sokuji_sidecar/catalog.py — keep in sync
# What a tts query adds to the set it is given (sk_ops_asked_weight_dtypes, src/sk_ops.h): f32,
# always asked (owner's ruling 2026-10-07), and f16 beside bf16 for a family on
# kRawTypedWeightFamilies, on Vulkan and Metal. A family off that list can only gain f32, so for
# it the bound is one dtype wider than it can reach.
TTS_ADDED_DTYPES = 2


def counts(path: pathlib.Path) -> tuple[int, int, int]:
    """(op lines, WEIGHT op lines, entries once every WEIGHT line expands over the widest set
    a query of the recording's stage can ask)."""
    body = [l for l in path.read_text(encoding="utf-8").splitlines() if l.startswith("op=")]
    weight = sum(1 for l in body if "WEIGHT" in l)
    widest = WIDEST_FALLBACK + (TTS_ADDED_DTYPES if path.stem.split("-", 1)[0] == "tts" else 0)
    return len(body), weight, weight * widest + (len(body) - weight)


def report(ops_dir: pathlib.Path, header: pathlib.Path) -> int:
    m = re.search(r"^#define SK_OP_COVERAGE_MAX (\d+)", header.read_text(encoding="utf-8"), re.MULTILINE)
    if m is None:
        print(f"gen_ops_data: no SK_OP_COVERAGE_MAX in {header}")
        return 2
    cap = int(m.group(1))
    over = 0
    for f in sorted(ops_dir.glob("*.ops")):
        ops, weight, expanded = counts(f)
        fits = expanded <= cap
        over += 0 if fits else 1
        print(f"{f.name}: {ops} op lines, {weight} WEIGHT, {expanded} expanded / cap {cap} {'ok' if fits else 'OVER'}")
    return 1 if over else 0


def generate(ops_dir: pathlib.Path, out: pathlib.Path, header: str) -> None:
    files = sorted(ops_dir.glob("*.ops"))
    lines = ['// GENERATED by cmake/gen_ops_data.py from src/ops/*.ops — do not edit.',
             f'#include "{header}"', '']
    for f in files:
        expanded = counts(f)[2]
        lines.append(f'static_assert({expanded} <= SK_OP_COVERAGE_MAX, "{f.name}: {expanded} expanded entries exceed SK_OP_COVERAGE_MAX");')
    lines += ['', 'const sk_ops_blob sk_ops_blobs[] = {']
    for f in files:
        stage, family = f.stem.split("-", 1)
        text = f.read_text(encoding="utf-8").replace("\\", "\\\\").replace('"', '\\"')
        body = "".join(f'    "{line}\\n"\n' for line in text.splitlines())
        lines.append(f'    {{ "{stage}", "{family}",\n{body}    }},')
    lines += ['};', f'const int sk_ops_blob_count_ = {len(files)};', '']
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"gen_ops_data: {len(files)} recordings -> {out}")


if __name__ == "__main__":
    if len(sys.argv) == 4 and sys.argv[1] == "--report":
        sys.exit(report(pathlib.Path(sys.argv[2]), pathlib.Path(sys.argv[3])))
    generate(pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2]), sys.argv[3])
